//! Decodes the golden fixtures in `tests/fixtures/` with the real codecs.
//!
//! `docs/TESTING.md` § Golden byte fixtures. These are bytes **Cloudflare's edge sent**, not
//! bytes this crate produced, which is what makes them worth anything: a fixture generated by
//! the code under test asserts only that the code agrees with itself.
//!
//! A failure here is one of three things and they are not interchangeable:
//!
//! 1. our decoder regressed — fix the decoder;
//! 2. the pinned cloudflared commit moved — update `docs/PROTOCOL.md` §1 and re-verify;
//! 3. **the edge changed** — an incident, because every installed client is affected
//!    (`docs/OPERATIONS.md`).
//!
//! Never "fix" a failure by re-capturing without deciding which of the three it was.

use nport_protocol::connect::{
    ConnectionType, StreamKind, read_connect_request, read_stream_kind, read_version,
};

/// Everything a fixture should tell us, decoded.
struct Decoded {
    kind: ConnectionType,
    dest: String,
    metadata: Vec<(String, String)>,
    /// Bytes left after the Cap'n Proto message. Must be zero for these fixtures: the tee that
    /// captured them stopped where the decoder stopped, so a non-zero value means the decoder
    /// now consumes a different amount than it did at capture time — exactly the bug that
    /// silently eats a request body (`docs/PROTOCOL.md` §11).
    trailing: usize,
}

async fn decode(name: &str) -> Decoded {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

    let mut reader: &[u8] = &bytes;
    assert_eq!(
        read_stream_kind(&mut reader).await.expect("signature"),
        StreamKind::Data,
        "{name} is not a data stream"
    );
    read_version(&mut reader).await.expect("version 01");
    let request = read_connect_request(&mut reader).await.expect("request");

    Decoded {
        kind: request.kind,
        dest: request.dest.clone(),
        metadata: request.metadata.clone(),
        trailing: reader.len(),
    }
}

fn value<'a>(metadata: &'a [(String, String)], key: &str) -> Option<&'a str> {
    metadata
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case(key))
        .map(|(_, v)| v.as_str())
}

#[tokio::test]
async fn http_request_from_the_live_edge_decodes() {
    let decoded = decode("connect_request_http.bin").await;

    assert_eq!(decoded.kind, ConnectionType::Http);
    assert!(decoded.dest.starts_with("https://"), "{}", decoded.dest);
    // The query string must survive — dropping it is invisible on a bare `/` and breaks
    // every real application.
    assert!(decoded.dest.contains("?q=1"), "{}", decoded.dest);
    assert_eq!(value(&decoded.metadata, "HttpMethod"), Some("GET"));
    assert!(value(&decoded.metadata, "HttpHost").is_some());
    assert_eq!(decoded.trailing, 0, "decoder over-read past the message");
}

#[tokio::test]
async fn the_edge_stamps_its_own_headers_on_every_request() {
    // Not decoration: these prove the fixture came from Cloudflare rather than from a local
    // encoder. If a future "capture" produced a file without them, it captured the wrong thing.
    let decoded = decode("connect_request_http.bin").await;
    for key in ["HttpHeader:Cf-Ray", "HttpHeader:Cdn-Loop"] {
        assert!(
            value(&decoded.metadata, key).is_some(),
            "{key} missing — is this really an edge capture?"
        );
    }
    assert_eq!(
        value(&decoded.metadata, "HttpHeader:Cdn-Loop"),
        Some("cloudflare; loops=1")
    );
}

#[tokio::test]
async fn no_fixture_contains_a_client_ip() {
    // The edge fills Cf-Connecting-Ip with the capturing machine's public address. These files
    // are committed to a public repository, so the capture redacts them in place. This test is
    // the guard against a future capture that forgets to.
    for name in ["connect_request_http.bin", "connect_request_websocket.bin"] {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name);
        let bytes = std::fs::read(&path).expect("fixture readable");
        let text = String::from_utf8_lossy(&bytes);

        for key in ["Cf-Connecting-Ip", "X-Forwarded-For", "True-Client-Ip"] {
            if let Some(found) = value(&decode_metadata(&bytes).await, &format!("HttpHeader:{key}"))
            {
                assert!(
                    found.starts_with("REDACTED"),
                    "{name}: {key} is {found}, which was not redacted"
                );
            }
        }
        // Belt and braces: no dotted quad anywhere in the file, whatever key it sits under.
        assert!(
            !contains_dotted_quad(&text),
            "{name} contains something shaped like an IPv4 address"
        );
    }
}

async fn decode_metadata(bytes: &[u8]) -> Vec<(String, String)> {
    let mut reader: &[u8] = bytes;
    read_stream_kind(&mut reader).await.expect("signature");
    read_version(&mut reader).await.expect("version");
    read_connect_request(&mut reader)
        .await
        .expect("request")
        .metadata
}

/// Deliberately crude — it should catch anything IP-shaped, including values this crate has
/// never seen. A false positive costs one look; a false negative publishes someone's address.
fn contains_dotted_quad(text: &str) -> bool {
    text.split(|c: char| !(c.is_ascii_digit() || c == '.'))
        .any(|candidate| {
            let parts: Vec<&str> = candidate.split('.').collect();
            parts.len() == 4
                && parts
                    .iter()
                    .all(|part| !part.is_empty() && part.len() <= 3 && part.parse::<u8>().is_ok())
        })
}

#[tokio::test]
async fn websocket_request_from_the_live_edge_decodes() {
    let decoded = decode("connect_request_websocket.bin").await;

    // The upgrade is signalled *only* by the type. There is no Connection or Upgrade header
    // in the metadata, which is why a proxy has to re-add them (§11).
    assert_eq!(decoded.kind, ConnectionType::Websocket);
    assert!(
        value(&decoded.metadata, "HttpHeader:Connection").is_none(),
        "the edge is now sending Connection — §11 needs revisiting"
    );
    assert!(
        value(&decoded.metadata, "HttpHeader:Upgrade").is_none(),
        "the edge is now sending Upgrade — §11 needs revisiting"
    );

    // The client's key must be present and forwarded: the origin derives Sec-Websocket-Accept
    // from it, so a proxy that drops or replaces it breaks every handshake.
    let key = value(&decoded.metadata, "HttpHeader:Sec-Websocket-Key")
        .expect("the edge forwards the client's key");
    assert!(!key.is_empty());
    assert_eq!(decoded.trailing, 0);
}

#[tokio::test]
async fn repeated_metadata_keys_are_preserved_as_a_list() {
    // A map keyed by header name would silently drop values here. Asserted against real edge
    // bytes rather than a synthetic message, because the edge's own duplication is the case
    // that matters.
    let decoded = decode("connect_request_http.bin").await;
    let keys: Vec<&str> = decoded.metadata.iter().map(|(k, _)| k.as_str()).collect();
    assert!(
        keys.len() > 5,
        "only {} metadata entries — suspiciously few",
        keys.len()
    );
}
