services:
  nport-server:
    build:
      context: .
      dockerfile: ./config/server.dockerfile
    image: nport-server:v1
    container_name: nport-server
    ports:
      - "3000:3000"
    volumes:
      - ./src/server:/app/src/server
    restart: unless-stopped
    networks:
      nport-network:
        ipv4_address: 192.168.10.3
    entrypoint: npm run server:dev

  nport-nginx:
    image: nginx:1.27.3-perl
    container_name: nport-nginx
    volumes:
      - /dev/null:/var/log/nginx/access.log
      - /dev/null:/var/log/nginx/error.log
      - ./config/nport.local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
    logging:
      driver: "none"
    networks:
      nport-network:
        ipv4_address: 192.168.10.2

  nport-site:
    build:
      context: .
      dockerfile: ./config/site.dockerfile
    image: nport-site:v1
    container_name: nport-site
    volumes:
      - ./src/site:/app/src/site
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      nport-network:
        ipv4_address: 192.168.10.5
    entrypoint: npm run website

  nport-client:
    build:
      context: .
      dockerfile: ./config/client.dockerfile
    image: nport-client:v1
    container_name: nport-client
    volumes:
      - ./src/client:/app/src/client
    restart: unless-stopped
    networks:
      nport-network:
        ipv4_address: 192.168.10.4
    entrypoint: npm run client:dev
    extra_hosts:
      - "nport.local:192.168.10.2"
      - "server.nport.local:192.168.10.2"
      - "myapp.nport.local:192.168.10.2"
      - "other.nport.local:192.168.10.2"
    depends_on:
      - nport-nginx
      - nport-server

networks:
  nport-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
