//! Generates `crates/contract` from the contract's JSON outputs.
//!
//! ```text
//! packages/contract  →  schema/nport-api.openapi.json  ┐
//!                    →  schema/errors.json             ┴→  crates/contract/src/generated.rs
//! ```
//!
//! **Why a purpose-built emitter rather than `typify`** (which ADR-0009 originally named): an
//! error's HTTP status and retryability are not expressible in JSON Schema, so `typify` could
//! only ever produce half of what the Rust client needs and a second generator would have to
//! produce the rest. One emitter reading two files is simpler than two pipelines, and the schemas
//! here are flat objects of strings, numbers, booleans, and string enums. See ADR-0025.
//!
//! The emitter **fails on any construct it does not recognise** rather than guessing. A generator
//! that silently emits the wrong type is worse than one that stops: the wrong type compiles, ships,
//! and misparses at runtime.

use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

const BANNER: &str = "@generated by `cargo xtask codegen` — do not edit";

pub fn run() -> Result<(), String> {
    let repo = repo_root()?;
    let openapi = read_json(&repo.join("schema/nport-api.openapi.json"))?;
    let registry = read_json(&repo.join("schema/errors.json"))?;

    let mut out = String::new();
    writeln!(out, "//! {BANNER}").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(
        out,
        "//! Source: `schema/nport-api.openapi.json` and `schema/errors.json`, themselves"
    )
    .unwrap();
    writeln!(
        out,
        "//! generated from `packages/contract`. Edit there and run `pnpm codegen && cargo xtask"
    )
    .unwrap();
    writeln!(out, "//! codegen`; CI fails on drift.\n").unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};\n").unwrap();

    emit_error_code(&mut out, &registry)?;
    emit_schemas(&mut out, &openapi)?;

    let target = repo.join("crates/contract/src/generated.rs");
    std::fs::write(&target, out).map_err(|e| format!("writing {}: {e}", target.display()))?;
    rustfmt(&target)?;
    println!("wrote {}", target.display());
    Ok(())
}

/// Formats the emitted file in place.
///
/// **Not cosmetic — the drift gate depends on it.** `codegen-drift.yml` regenerates and then runs
/// `git diff --exit-code`, so if the raw output differs from what `cargo fmt` would produce by even
/// one line, CI fails on a tree nobody touched. Caught exactly that way: the generator's output was
/// one newline away from canonical.
fn rustfmt(path: &Path) -> Result<(), String> {
    let status = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .arg(path)
        .status();

    match status {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => Err(format!("rustfmt exited with {status}")),
        // Not fatal: a source tarball may have no rustfmt, and unformatted-but-correct output
        // still compiles. The drift gate will complain, which is the right place to notice.
        Err(error) => {
            eprintln!("xtask codegen: could not run rustfmt ({error}); output left unformatted");
            Ok(())
        }
    }
}

pub fn repo_root() -> Result<PathBuf, String> {
    // CARGO_MANIFEST_DIR is crates/xtask, so the root is two levels up. Deliberately not
    // `git rev-parse`: codegen must work in a source tarball with no git directory.
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .ok_or_else(|| "could not locate the repository root".to_owned())
}

fn read_json(path: &Path) -> Result<Value, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("reading {}: {e} — run `pnpm codegen` first", path.display()))?;
    serde_json::from_str(&text).map_err(|e| format!("parsing {}: {e}", path.display()))
}

/// `SUBDOMAIN_IN_USE` → `SubdomainInUse`.
fn variant_name(code: &str) -> String {
    code.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => format!(
                    "{}{}",
                    first.to_ascii_uppercase(),
                    chars.as_str().to_ascii_lowercase()
                ),
                None => String::new(),
            }
        })
        .collect()
}

fn emit_error_code(out: &mut String, registry: &Value) -> Result<(), String> {
    let errors = registry
        .get("errors")
        .and_then(Value::as_object)
        .ok_or("schema/errors.json has no `errors` object")?;

    writeln!(
        out,
        "/// Every error the control plane can return, or the client can raise."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// **Match on this, never on a message.** Messages are translated and free to change;"
    )
    .unwrap();
    writeln!(
        out,
        "/// codes are the contract (ADR-0018). `serde` uses the wire spelling."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(out, "#[non_exhaustive]").unwrap();
    writeln!(out, "pub enum ErrorCode {{").unwrap();
    for (code, definition) in errors {
        let message = definition
            .get("message")
            .and_then(Value::as_str)
            .unwrap_or_default();
        writeln!(out, "    /// {message}").unwrap();
        writeln!(out, "    #[serde(rename = \"{code}\")]").unwrap();
        writeln!(out, "    {},", variant_name(code)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    // ALL, so a caller can iterate without the enum being exhaustively matchable.
    writeln!(out, "impl ErrorCode {{").unwrap();
    writeln!(out, "    /// Every code, in registry order.").unwrap();
    writeln!(out, "    pub const ALL: [Self; {}] = [", errors.len()).unwrap();
    for code in errors.keys() {
        writeln!(out, "        Self::{},", variant_name(code)).unwrap();
    }
    writeln!(out, "    ];\n").unwrap();

    writeln!(out, "    /// The wire spelling, e.g. `SUBDOMAIN_IN_USE`.").unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn as_str(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for code in errors.keys() {
        writeln!(
            out,
            "            Self::{} => \"{code}\",",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(out, "    /// The docs slug, e.g. `subdomain-in-use`.").unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn slug(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for (code, definition) in errors {
        let slug = definition.get("slug").and_then(Value::as_str).unwrap_or("");
        writeln!(
            out,
            "            Self::{} => \"{slug}\",",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// HTTP status, or `None` for a client-side code that never crosses the network."
    )
    .unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn http_status(self) -> Option<u16> {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for (code, definition) in errors {
        let status = definition.get("status").and_then(Value::as_u64);
        let rendered = match status {
            Some(status) => format!("Some({status})"),
            None => "None".to_owned(),
        };
        writeln!(
            out,
            "            Self::{} => {rendered},",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// Whether retrying the same request can succeed."
    )
    .unwrap();
    writeln!(out, "    ///").unwrap();
    writeln!(
        out,
        "    /// Not advisory — `crates/cli` branches on it, so a wrong value either hammers a"
    )
    .unwrap();
    writeln!(
        out,
        "    /// permanent failure or gives up on a transient one."
    )
    .unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn is_retryable(self) -> bool {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for (code, definition) in errors {
        let retryable = definition
            .get("retryable")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        writeln!(
            out,
            "            Self::{} => {retryable},",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// Parses a wire code. Unknown codes are `None`, never a guess."
    )
    .unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub fn parse(code: &str) -> Option<Self> {{").unwrap();
    writeln!(out, "        match code {{").unwrap();
    for code in errors.keys() {
        writeln!(
            out,
            "            \"{code}\" => Some(Self::{}),",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}\n    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    writeln!(out, "impl std::fmt::Display for ErrorCode {{").unwrap();
    writeln!(
        out,
        "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{"
    )
    .unwrap();
    writeln!(out, "        f.write_str(self.as_str())").unwrap();
    writeln!(out, "    }}\n}}\n").unwrap();

    Ok(())
}

fn emit_schemas(out: &mut String, openapi: &Value) -> Result<(), String> {
    let schemas = openapi
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .ok_or("the OpenAPI document has no components.schemas")?;

    // Named string enums, indexed by their value set.
    //
    // zod inlines a reused enum rather than emitting a `$ref`, so `CreateTunnelRequest.client`
    // arrives as `{type: "string", enum: ["cli", "desktop"]}` with no hint that `ClientKind`
    // exists. Emitting `String` for it would hand callers exactly the stringly-typed matching the
    // contract exists to prevent, so the enum is resolved back to its named type here.
    let mut enum_names: HashMap<Vec<String>, String> = HashMap::new();
    for (name, schema) in schemas {
        if let Some(values) = schema.get("enum").and_then(Value::as_array) {
            let mut set: Vec<String> = values
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect();
            set.sort();
            enum_names.insert(set, name.clone());
        }
    }

    // BTreeMap so the output order is stable regardless of the input's key order — a generator
    // whose output reorders between runs makes the drift gate useless.
    let ordered: BTreeMap<&String, &Value> = schemas.iter().collect();

    for (name, schema) in ordered {
        // `Error` is the envelope; its `code` field is the enum above, and the envelope itself is
        // hand-written in lib.rs so it can carry a typed `ErrorCode` rather than a String.
        if name == "Error" {
            continue;
        }
        emit_type(out, name, schema, &enum_names)?;
    }
    Ok(())
}

fn emit_type(
    out: &mut String,
    name: &str,
    schema: &Value,
    enum_names: &HashMap<Vec<String>, String>,
) -> Result<(), String> {
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return emit_string_enum(out, name, values);
    }

    let kind = schema.get("type").and_then(Value::as_str).unwrap_or("");
    if kind != "object" {
        return Err(format!(
            "{name}: only objects and string enums are supported at the top level, got {kind:?}"
        ));
    }

    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| format!("{name}: object schema with no properties"))?;
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|items| items.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    // **A struct holding a credential does not get a derived `Debug`.**
    // `docs/conventions/rust.md`: "Never `#[derive(Debug)]` on a struct holding a token or secret."
    // `CreateTunnelResponse` carries both the `ownerToken` and the connector `tunnelToken`, and the
    // generated field's own doc comment says "Never logged" — a derive contradicting the line above it.
    // Nothing formats one today, so this closes the hole before it is a leak rather than after.
    //
    // Decided from the field name, not a list of struct names kept here. `*Token` is this contract's
    // word for a credential, so a field added tomorrow is covered without anyone remembering to come
    // back — the failure mode of every hand-maintained list in this repository.
    let secrets: Vec<String> = properties
        .keys()
        .filter(|property| property.to_ascii_lowercase().ends_with("token"))
        .map(|property| snake_case(property))
        .collect();

    if let Some(description) = schema.get("description").and_then(Value::as_str) {
        writeln!(out, "/// {description}").unwrap();
    }
    if secrets.is_empty() {
        writeln!(
            out,
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
        )
        .unwrap();
    } else {
        writeln!(out, "#[derive(Clone, PartialEq, Serialize, Deserialize)]").unwrap();
    }
    writeln!(out, "#[serde(rename_all = \"camelCase\")]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();

    for (property, definition) in properties {
        let rust_type = rust_type_for(name, property, definition, enum_names)?;
        let optional = !required.contains(&property.as_str());
        if let Some(description) = definition.get("description").and_then(Value::as_str) {
            writeln!(out, "    /// {description}").unwrap();
        }
        let field = snake_case(property);
        if field != *property {
            // rename_all handles camelCase, but a name like `powDifficulty` → `pow_difficulty`
            // only round-trips if serde agrees; asserting it per field costs nothing and makes a
            // mismatch a compile-time artifact rather than a runtime one.
            writeln!(out, "    #[serde(rename = \"{property}\")]").unwrap();
        }
        if optional {
            // **An absent field must serialize as absent, not as `null`.** The contract expresses
            // optionality with zod's `.optional()`, which accepts a missing key and *rejects*
            // `null` — that is `.nullable()`, a different thing. Without this attribute, a `None`
            // goes out as `"subdomain": null` and the server answers `INVALID_REQUEST`.
            //
            // Not hypothetical: it made `nport 3000` — the most common invocation there is, the one
            // that asks the server to generate a name — fail with a 400 against every backend. Every
            // test and every manual run had passed `-s`, so nothing caught it until someone ran the
            // command the README leads with.
            writeln!(
                out,
                "    #[serde(skip_serializing_if = \"Option::is_none\")]"
            )
            .unwrap();
            writeln!(out, "    pub {field}: Option<{rust_type}>,").unwrap();
        } else {
            writeln!(out, "    pub {field}: {rust_type},").unwrap();
        }
    }
    writeln!(out, "}}\n").unwrap();

    if !secrets.is_empty() {
        // Redacting rather than absent: `Debug` is what a consumer reaches for when a request looks
        // wrong, and removing it entirely pushes them toward printing the fields one by one — which is
        // how the secret ends up in a log anyway. The shape matches `TunnelToken` in
        // `crates/protocol/src/token.rs`, which solved this once already for the parsed credential.
        writeln!(out, "impl std::fmt::Debug for {name} {{").unwrap();
        writeln!(
            out,
            "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{"
        )
        .unwrap();
        writeln!(out, "        f.debug_struct(\"{name}\")").unwrap();
        for (property, definition) in properties {
            let field = snake_case(property);
            let optional = !required.contains(&property.as_str());
            if secrets.contains(&field) {
                writeln!(out, "            .field(\"{field}\", &\"<redacted>\")").unwrap();
            } else {
                let _ = definition;
                let _ = optional;
                writeln!(out, "            .field(\"{field}\", &self.{field})").unwrap();
            }
        }
        writeln!(out, "            .finish()").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    Ok(())
}

fn emit_string_enum(out: &mut String, name: &str, values: &[Value]) -> Result<(), String> {
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(out, "pub enum {name} {{").unwrap();
    for value in values {
        let text = value
            .as_str()
            .ok_or_else(|| format!("{name}: enum values must be strings"))?;
        writeln!(out, "    #[serde(rename = \"{text}\")]").unwrap();
        writeln!(out, "    {},", variant_name(&text.to_uppercase())).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    Ok(())
}

fn rust_type_for(
    owner: &str,
    property: &str,
    definition: &Value,
    enum_names: &HashMap<Vec<String>, String>,
) -> Result<String, String> {
    if let Some(reference) = definition.get("$ref").and_then(Value::as_str) {
        let name = reference.rsplit('/').next().unwrap_or_default();
        return Ok(name.to_owned());
    }

    // An inlined enum must resolve to a named type. Falling back to `String` would compile and
    // then accept any value the contract forbids, so an unnamed enum is a codegen failure.
    if let Some(values) = definition.get("enum").and_then(Value::as_array) {
        let mut set: Vec<String> = values
            .iter()
            .filter_map(Value::as_str)
            .map(str::to_owned)
            .collect();
        set.sort();
        return enum_names.get(&set).cloned().ok_or_else(|| {
            format!(
                "{owner}.{property}: inline enum {set:?} has no named component. \
                 Add it to COMPONENTS in packages/contract/scripts/codegen.ts so it gets a type."
            )
        });
    }

    match definition.get("type").and_then(Value::as_str) {
        Some("string") => Ok("String".to_owned()),
        Some("boolean") => Ok("bool".to_owned()),
        // Every integer in this contract is a timestamp, a count, or a difficulty — all
        // non-negative and all comfortably inside u64.
        Some("integer") => Ok("u64".to_owned()),
        Some("number") => Ok("f64".to_owned()),
        // `details` is an open map of arbitrary JSON, which is the one place the contract is
        // deliberately untyped: its shape depends on the error code.
        Some("object") => Ok("serde_json::Map<String, serde_json::Value>".to_owned()),
        other => Err(format!(
            "{owner}.{property}: unsupported JSON Schema type {other:?}. \
             Extend crates/xtask/src/codegen.rs rather than letting it guess."
        )),
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (index, ch) in name.char_indices() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
