//! Generates `crates/contract` from the contract's JSON outputs.
//!
//! ```text
//! packages/contract  →  schema/nport-node.openapi.json       ┐
//!                    →  schema/nport-registry.openapi.json  │
//!                    →  schema/errors.json                  ├→  crates/contract/src/generated.rs
//!                    →  schema/subdomain.json               ┘
//! ```
//!
//! **Why a purpose-built emitter rather than `typify`** (which ADR-0009 originally named): an
//! error's HTTP status and retryability are not expressible in JSON Schema, so `typify` could
//! only ever produce half of what the Rust client needs and a second generator would have to
//! produce the rest. One emitter reading four files is simpler than four pipelines, and the schemas
//! here are flat objects of strings, numbers, booleans, string enums, and arrays of those.
//! See ADR-0025.
//!
//! **Two of the four are service documents** — the control plane and the registry (ADR-0046) — and
//! one Rust crate mirrors both, because `crates/core` is a client of both: it provisions against a
//! node and discovers through the registry. `schema/subdomain.json` carries the subdomain rules'
//! **constants** for the hand-written mirror in `crates/contract/src/subdomain.rs`; its rules are not
//! generated, and [`emit_subdomain_rules`] says why.
//!
//! The emitter **fails on any construct it does not recognise** rather than guessing. A generator
//! that silently emits the wrong type is worse than one that stops: the wrong type compiles, ships,
//! and misparses at runtime.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

const BANNER: &str = "@generated by `cargo xtask codegen` — do not edit";

pub fn run() -> Result<(), String> {
    let repo = repo_root()?;
    let openapi = read_json(&repo.join("schema/nport-node.openapi.json"))?;
    let registry_api = read_json(&repo.join("schema/nport-registry.openapi.json"))?;
    let registry = read_json(&repo.join("schema/errors.json"))?;
    let subdomain = read_json(&repo.join("schema/subdomain.json"))?;

    let mut out = String::new();
    writeln!(out, "//! {BANNER}").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(
        out,
        "//! Source: the two service documents in `schema/`, plus `schema/errors.json` and"
    )
    .unwrap();
    writeln!(
        out,
        "//! `schema/subdomain.json` — themselves generated from `packages/contract`. Edit there"
    )
    .unwrap();
    writeln!(
        out,
        "//! and run `pnpm codegen && cargo xtask codegen`; CI fails on drift.\n"
    )
    .unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};\n").unwrap();

    emit_error_code(&mut out, &registry)?;
    emit_schemas(&mut out, &[&openapi, &registry_api])?;
    emit_subdomain_rules(&mut out, &subdomain)?;

    let target = repo.join("crates/contract/src/generated.rs");
    std::fs::write(&target, out).map_err(|e| format!("writing {}: {e}", target.display()))?;
    rustfmt(&target)?;
    println!("wrote {}", target.display());

    // The CLI reference goes the other way — read from Rust, written into `schema/` — so it is not part
    // of the pipeline above and is emitted separately. `crates/xtask/src/cli_reference.rs` says why it is
    // generated at all.
    let reference = repo.join("schema/cli.json");
    std::fs::write(&reference, crate::cli_reference::render()?)
        .map_err(|e| format!("writing {}: {e}", reference.display()))?;
    println!("wrote {}", reference.display());

    Ok(())
}

/// Formats the emitted file in place.
///
/// **Not cosmetic — the drift gate depends on it.** `codegen-drift.yml` regenerates and then runs
/// `git diff --exit-code`, so if the raw output differs from what `cargo fmt` would produce by even
/// one line, CI fails on a tree nobody touched. Caught exactly that way: the generator's output was
/// one newline away from canonical.
fn rustfmt(path: &Path) -> Result<(), String> {
    let status = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .arg(path)
        .status();

    match status {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => Err(format!("rustfmt exited with {status}")),
        // Not fatal: a source tarball may have no rustfmt, and unformatted-but-correct output
        // still compiles. The drift gate will complain, which is the right place to notice.
        Err(error) => {
            eprintln!("xtask codegen: could not run rustfmt ({error}); output left unformatted");
            Ok(())
        }
    }
}

pub fn repo_root() -> Result<PathBuf, String> {
    // CARGO_MANIFEST_DIR is crates/xtask, so the root is two levels up. Deliberately not
    // `git rev-parse`: codegen must work in a source tarball with no git directory.
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .ok_or_else(|| "could not locate the repository root".to_owned())
}

fn read_json(path: &Path) -> Result<Value, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("reading {}: {e} — run `pnpm codegen` first", path.display()))?;
    serde_json::from_str(&text).map_err(|e| format!("parsing {}: {e}", path.display()))
}

/// `SUBDOMAIN_IN_USE` → `SubdomainInUse`.
fn variant_name(code: &str) -> String {
    code.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => format!(
                    "{}{}",
                    first.to_ascii_uppercase(),
                    chars.as_str().to_ascii_lowercase()
                ),
                None => String::new(),
            }
        })
        .collect()
}

fn emit_error_code(out: &mut String, registry: &Value) -> Result<(), String> {
    let errors = registry
        .get("errors")
        .and_then(Value::as_object)
        .ok_or("schema/errors.json has no `errors` object")?;

    writeln!(
        out,
        "/// Every error the control plane can return, or the client can raise."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// **Match on this, never on a message.** Messages are translated and free to change;"
    )
    .unwrap();
    writeln!(
        out,
        "/// codes are the contract (ADR-0018). `serde` uses the wire spelling."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(out, "#[non_exhaustive]").unwrap();
    writeln!(out, "pub enum ErrorCode {{").unwrap();
    for (code, definition) in errors {
        let message = definition
            .get("message")
            .and_then(Value::as_str)
            .unwrap_or_default();
        writeln!(out, "    /// {message}").unwrap();
        writeln!(out, "    #[serde(rename = \"{code}\")]").unwrap();
        writeln!(out, "    {},", variant_name(code)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    // ALL, so a caller can iterate without the enum being exhaustively matchable.
    writeln!(out, "impl ErrorCode {{").unwrap();
    // Alphabetical, not the registry's own order: `serde_json`'s `Value` is a `BTreeMap` here, so it
    // sorts the keys on the way in. Said accurately because this comment claimed "registry order" for
    // as long as the emitter has existed. Nothing depends on either order — every caller iterates —
    // and alphabetical is the more stable of the two, since it does not move when a code is inserted
    // into the middle of the registry.
    writeln!(out, "    /// Every code, alphabetically.").unwrap();
    writeln!(out, "    pub const ALL: [Self; {}] = [", errors.len()).unwrap();
    for code in errors.keys() {
        writeln!(out, "        Self::{},", variant_name(code)).unwrap();
    }
    writeln!(out, "    ];\n").unwrap();

    writeln!(out, "    /// The wire spelling, e.g. `SUBDOMAIN_IN_USE`.").unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn as_str(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for code in errors.keys() {
        writeln!(
            out,
            "            Self::{} => \"{code}\",",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(out, "    /// The docs slug, e.g. `subdomain-in-use`.").unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn slug(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for (code, definition) in errors {
        let slug = definition.get("slug").and_then(Value::as_str).unwrap_or("");
        writeln!(
            out,
            "            Self::{} => \"{slug}\",",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// HTTP status, or `None` for a client-side code that never crosses the network."
    )
    .unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn http_status(self) -> Option<u16> {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for (code, definition) in errors {
        let status = definition.get("status").and_then(Value::as_u64);
        let rendered = match status {
            Some(status) => format!("Some({status})"),
            None => "None".to_owned(),
        };
        writeln!(
            out,
            "            Self::{} => {rendered},",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// Whether retrying the same request can succeed."
    )
    .unwrap();
    writeln!(out, "    ///").unwrap();
    writeln!(
        out,
        "    /// Not advisory — `crates/cli` branches on it, so a wrong value either hammers a"
    )
    .unwrap();
    writeln!(
        out,
        "    /// permanent failure or gives up on a transient one."
    )
    .unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub const fn is_retryable(self) -> bool {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for (code, definition) in errors {
        let retryable = definition
            .get("retryable")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        writeln!(
            out,
            "            Self::{} => {retryable},",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// Parses a wire code. Unknown codes are `None`, never a guess."
    )
    .unwrap();
    writeln!(out, "    #[must_use]").unwrap();
    writeln!(out, "    pub fn parse(code: &str) -> Option<Self> {{").unwrap();
    writeln!(out, "        match code {{").unwrap();
    for code in errors.keys() {
        writeln!(
            out,
            "            \"{code}\" => Some(Self::{}),",
            variant_name(code)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}\n    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    writeln!(out, "impl std::fmt::Display for ErrorCode {{").unwrap();
    writeln!(
        out,
        "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{"
    )
    .unwrap();
    writeln!(out, "        f.write_str(self.as_str())").unwrap();
    writeln!(out, "    }}\n}}\n").unwrap();

    Ok(())
}

/// Emits one Rust type per named component, across **every** service document.
///
/// There are two — the control plane and the registry (ADR-0046) — and one Rust crate mirrors both,
/// because `crates/core` is a client of both: it provisions against a node and discovers through the
/// registry. Merging here rather than generating two modules keeps `nport_contract::Node` a single
/// path.
///
/// A name appearing in both documents must mean the same thing in both. `ChallengeResponse` does
/// appear twice, since both services gate writes with proof of work — so equality is **checked**
/// rather than assumed, and a genuine collision is a hard error. Silently letting one definition win
/// is how two services drift into disagreeing about a shape while the generated code shows only one.
fn emit_schemas(out: &mut String, documents: &[&Value]) -> Result<(), String> {
    // BTreeMap so the output order is stable regardless of the input's key order — a generator
    // whose output reorders between runs makes the drift gate useless.
    let mut merged: BTreeMap<String, &Value> = BTreeMap::new();

    for document in documents {
        let schemas = document
            .pointer("/components/schemas")
            .and_then(Value::as_object)
            .ok_or("an OpenAPI document has no components.schemas")?;

        for (name, schema) in schemas {
            if let Some(existing) = merged.get(name) {
                if *existing != schema {
                    return Err(format!(
                        "{name} is defined differently in two service documents. One name must mean \
                         one shape — rename one, or make them identical in packages/contract."
                    ));
                }
                continue;
            }
            merged.insert(name.clone(), schema);
        }
    }

    for (name, schema) in merged {
        // `Error` is the envelope; its `code` field is the error enum, and the envelope itself is
        // hand-written in lib.rs so it can carry a typed `ErrorCode` rather than a String.
        if name == "Error" {
            continue;
        }
        emit_type(out, &name, schema)?;
    }
    Ok(())
}

fn emit_type(out: &mut String, name: &str, schema: &Value) -> Result<(), String> {
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return emit_string_enum(out, name, values);
    }

    let kind = schema.get("type").and_then(Value::as_str).unwrap_or("");
    if kind != "object" {
        return Err(format!(
            "{name}: only objects and string enums are supported at the top level, got {kind:?}"
        ));
    }

    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| format!("{name}: object schema with no properties"))?;
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|items| items.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    // **A struct holding a credential does not get a derived `Debug`.**
    // `docs/conventions/rust.md`: "Never `#[derive(Debug)]` on a struct holding a token or secret."
    // `CreateTunnelResponse` carries both the `ownerToken` and the connector `tunnelToken`, and the
    // generated field's own doc comment says "Never logged" — a derive contradicting the line above it.
    // Nothing formats one today, so this closes the hole before it is a leak rather than after.
    //
    // Decided from the field name, not a list of struct names kept here. `*Token` is this contract's
    // word for a credential, so a field added tomorrow is covered without anyone remembering to come
    // back — the failure mode of every hand-maintained list in this repository.
    let secrets: Vec<String> = properties
        .keys()
        .filter(|property| property.to_ascii_lowercase().ends_with("token"))
        .map(|property| snake_case(property))
        .collect();

    if let Some(description) = schema.get("description").and_then(Value::as_str) {
        writeln!(out, "/// {description}").unwrap();
    }
    if secrets.is_empty() {
        writeln!(
            out,
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
        )
        .unwrap();
    } else {
        writeln!(out, "#[derive(Clone, PartialEq, Serialize, Deserialize)]").unwrap();
    }
    writeln!(out, "#[serde(rename_all = \"camelCase\")]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();

    for (property, definition) in properties {
        let rust_type = rust_type_for(name, property, definition)?;
        let optional = !required.contains(&property.as_str());
        if let Some(description) = definition.get("description").and_then(Value::as_str) {
            writeln!(out, "    /// {description}").unwrap();
        }
        let field = snake_case(property);
        if field != *property {
            // rename_all handles camelCase, but a name like `powDifficulty` → `pow_difficulty`
            // only round-trips if serde agrees; asserting it per field costs nothing and makes a
            // mismatch a compile-time artifact rather than a runtime one.
            writeln!(out, "    #[serde(rename = \"{property}\")]").unwrap();
        }
        if optional {
            // **An absent field must serialize as absent, not as `null`.** The contract expresses
            // optionality with zod's `.optional()`, which accepts a missing key and *rejects*
            // `null` — that is `.nullable()`, a different thing. Without this attribute, a `None`
            // goes out as `"subdomain": null` and the server answers `INVALID_REQUEST`.
            //
            // Not hypothetical: it made `nport 3000` — the most common invocation there is, the one
            // that asks the server to generate a name — fail with a 400 against every backend. Every
            // test and every manual run had passed `-s`, so nothing caught it until someone ran the
            // command the README leads with.
            writeln!(
                out,
                "    #[serde(skip_serializing_if = \"Option::is_none\")]"
            )
            .unwrap();
            writeln!(out, "    pub {field}: Option<{rust_type}>,").unwrap();
        } else {
            writeln!(out, "    pub {field}: {rust_type},").unwrap();
        }
    }
    writeln!(out, "}}\n").unwrap();

    if !secrets.is_empty() {
        // Redacting rather than absent: `Debug` is what a consumer reaches for when a request looks
        // wrong, and removing it entirely pushes them toward printing the fields one by one — which is
        // how the secret ends up in a log anyway. The shape matches `TunnelToken` in
        // `crates/protocol/src/token.rs`, which solved this once already for the parsed credential.
        writeln!(out, "impl std::fmt::Debug for {name} {{").unwrap();
        writeln!(
            out,
            "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{"
        )
        .unwrap();
        writeln!(out, "        f.debug_struct(\"{name}\")").unwrap();
        for (property, definition) in properties {
            let field = snake_case(property);
            let optional = !required.contains(&property.as_str());
            if secrets.contains(&field) {
                writeln!(out, "            .field(\"{field}\", &\"<redacted>\")").unwrap();
            } else {
                let _ = definition;
                let _ = optional;
                writeln!(out, "            .field(\"{field}\", &self.{field})").unwrap();
            }
        }
        writeln!(out, "            .finish()").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}\n").unwrap();
    }

    Ok(())
}

fn emit_string_enum(out: &mut String, name: &str, values: &[Value]) -> Result<(), String> {
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(out, "pub enum {name} {{").unwrap();
    for value in values {
        let text = value
            .as_str()
            .ok_or_else(|| format!("{name}: enum values must be strings"))?;
        writeln!(out, "    #[serde(rename = \"{text}\")]").unwrap();
        writeln!(out, "    {},", variant_name(&text.to_uppercase())).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    Ok(())
}

fn rust_type_for(owner: &str, property: &str, definition: &Value) -> Result<String, String> {
    if let Some(reference) = definition.get("$ref").and_then(Value::as_str) {
        let name = reference.rsplit('/').next().unwrap_or_default();
        return Ok(name.to_owned());
    }

    // An inlined enum is a codegen failure, not something to resolve.
    //
    // This used to look the value set up among the named components, because zod inlined a reused
    // enum with no hint that a named type existed. `packages/contract` now converts every component
    // through a zod registry, so a named enum arrives as a `$ref` and is handled above — which left
    // the lookup unreachable. Deleting it outright would have been wrong: without this branch an
    // inline enum falls through to `Some("string")` below and quietly becomes a `String`, accepting
    // every value the contract forbids. That is exactly the silent-wrong-type failure this emitter
    // promises not to commit, so the dead resolution became a live refusal.
    if let Some(values) = definition.get("enum").and_then(Value::as_array) {
        let set: Vec<&str> = values.iter().filter_map(Value::as_str).collect();
        return Err(format!(
            "{owner}.{property}: inline enum {set:?} has no named component. Add it to COMPONENTS \
             in packages/contract/scripts/codegen.ts so it is emitted as a type and referenced."
        ));
    }

    // `Vec<T>`, where T comes back through this same function — so an array of `$ref` gives
    // `Vec<Node>` and an array of strings gives `Vec<String>`, without a second type mapping to keep
    // in step. An array with no `items` is a schema that says nothing about its contents, and
    // guessing `Vec<serde_json::Value>` for it would hide a contract mistake behind a type that
    // deserializes anything.
    if definition.get("type").and_then(Value::as_str) == Some("array") {
        let items = definition.get("items").ok_or_else(|| {
            format!("{owner}.{property}: array with no `items` — nothing says what it holds")
        })?;
        return Ok(format!("Vec<{}>", rust_type_for(owner, property, items)?));
    }

    match definition.get("type").and_then(Value::as_str) {
        Some("string") => Ok("String".to_owned()),
        Some("boolean") => Ok("bool".to_owned()),
        // Every integer in this contract is a timestamp, a count, or a difficulty — all
        // non-negative and all comfortably inside u64.
        Some("integer") => Ok("u64".to_owned()),
        Some("number") => Ok("f64".to_owned()),
        // `details` is an open map of arbitrary JSON, which is the one place the contract is
        // deliberately untyped: its shape depends on the error code.
        Some("object") => Ok("serde_json::Map<String, serde_json::Value>".to_owned()),
        other => Err(format!(
            "{owner}.{property}: unsupported JSON Schema type {other:?}. \
             Extend crates/xtask/src/codegen.rs rather than letting it guess."
        )),
    }
}

/// The subdomain rules' **constants**, for the hand-written mirror in `crates/contract`.
///
/// Emitted rather than retyped because of what is in them: `RESERVED_SUBDOMAINS` is 53 names, and a
/// second copy maintained by hand is the shape of `docs/ROADMAP.md`'s defects 22, 25 and 29 — a list
/// standing behind a guarantee, correct only until somebody forgets. Adding a name in
/// `packages/contract` has to be sufficient, and this is what makes it sufficient.
///
/// **Only the constants.** The rules that use them are reimplemented in Rust and pinned by
/// `packages/contract/fixtures/subdomains.json`, which both test suites read. Emitting NFKC and a
/// suffix strip into another language would be a generator nobody should have to debug.
fn emit_subdomain_rules(out: &mut String, rules: &Value) -> Result<(), String> {
    fn number(rules: &Value, key: &str) -> Result<u64, String> {
        rules
            .get(key)
            .and_then(Value::as_u64)
            .ok_or_else(|| format!("schema/subdomain.json has no numeric `{key}`"))
    }

    fn strings(rules: &Value, key: &str) -> Result<Vec<String>, String> {
        let array = rules
            .get(key)
            .and_then(Value::as_array)
            .ok_or_else(|| format!("schema/subdomain.json has no array `{key}`"))?;
        array
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .map(str::to_owned)
                    // Not a `filter_map`: silently dropping a non-string would silently drop a
                    // reserved name, which is the one failure this whole file exists to prevent.
                    .ok_or_else(|| format!("schema/subdomain.json: `{key}` holds a non-string"))
            })
            .collect()
    }

    let zone_suffix = rules
        .get("zoneSuffix")
        .and_then(Value::as_str)
        .ok_or("schema/subdomain.json has no `zoneSuffix`")?;

    writeln!(
        out,
        "// ── Subdomain rules, from `schema/subdomain.json` ─────────────────────────────────\n"
    )
    .unwrap();

    writeln!(
        out,
        "/// The shortest claimable name. Ours, not DNS's — it keeps the namespace sane."
    )
    .unwrap();
    writeln!(
        out,
        "pub const MIN_SUBDOMAIN_LENGTH: usize = {};",
        number(rules, "minLength")?
    )
    .unwrap();
    writeln!(out, "/// The DNS label limit.").unwrap();
    writeln!(
        out,
        "pub const MAX_SUBDOMAIN_LENGTH: usize = {};",
        number(rules, "maxLength")?
    )
    .unwrap();
    writeln!(
        out,
        "/// The longest **raw input** normalization will look at, before the zone suffix is stripped."
    )
    .unwrap();
    writeln!(
        out,
        "pub const MAX_SUBDOMAIN_INPUT_LENGTH: usize = {};",
        number(rules, "maxInputLength")?
    )
    .unwrap();
    writeln!(
        out,
        "/// Stripped during normalization, so pasting a whole hostname works."
    )
    .unwrap();
    writeln!(out, "pub const ZONE_SUFFIX: &str = {zone_suffix:?};\n").unwrap();

    for (key, name, doc) in [
        (
            "reservedSubdomains",
            "RESERVED_SUBDOMAINS",
            "Names nobody may claim.",
        ),
        (
            "reservedPrefixes",
            "RESERVED_PREFIXES",
            "Prefixes nobody may claim.",
        ),
        (
            "nportOwnedPrefixes",
            "NPORT_OWNED_PREFIXES",
            "The reserved prefixes that are NPort's own, and therefore ours to reap (ADR-0036).",
        ),
        (
            "rejectionReasons",
            "REJECTION_REASONS",
            "Every `details.reason` a refusal can carry, in the contract's own spelling.",
        ),
    ] {
        let values = strings(rules, key)?;
        writeln!(out, "/// {doc}").unwrap();
        writeln!(out, "pub const {name}: [&str; {}] = [", values.len()).unwrap();
        for value in &values {
            writeln!(out, "    {value:?},").unwrap();
        }
        writeln!(out, "];\n").unwrap();
    }

    Ok(())
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (index, ch) in name.char_indices() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
