name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `nport 3000 -s mysubdomain`
        2. Wait for connection...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Screenshots
      description: If applicable, paste error logs or add screenshots.
      placeholder: Paste logs here...
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version` to get this.
      placeholder: "v20.10.0"
    validations:
      required: true

  - type: input
    id: nport-version
    attributes:
      label: NPort Version
      description: Run `nport --version` to get this.
      placeholder: "2.1.1"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of NPort
          required: false
