import { invoke } from "@tauri-apps/api/core"

/**
 * A thin wrapper over one Tauri command.
 *
 * Wrappers rather than `invoke` at the call site, per `apps/desktop/CLAUDE.md`: from Phase 4 these
 * are typed by `src/generated/bindings.ts`, generated by `tauri-specta` from the Rust signatures, so
 * a renamed command fails at `tsc` rather than at runtime. Until that exists the shape is hand-typed
 * here, which is the one place it has to be kept honest by reading `src-tauri/src/lib.rs`.
 */
export async function greet(): Promise<string> {
  return await invoke<string>("health")
}
