/**
 * Generates everything downstream of the contract.
 *
 * ```
 * pnpm --filter @nport/contract codegen     # or: pnpm codegen, from the root
 * ```
 *
 * Outputs, each with a `@generated` banner and each drift-gated in CI:
 *
 * - `docs/ERRORS.md`               — the registry as a human-readable table
 * - `schema/nport-api.openapi.json` — the API contract, which in turn generates `crates/contract`
 *
 * Run under `tsx`. Node 22 strips types on its own, but its ESM resolver still requires explicit
 * extensions on relative imports, and `docs/conventions/typescript.md` forbids those — a runner
 * that resolves them is a cheaper fix than extension-annotating every source file to suit a
 * script.
 *
 * **Prose that is not derived from the registry lives in this file**, because these outputs are
 * generated whole rather than having sections spliced into a hand-written file. Splicing needs
 * markers, markers get moved, and a generator that silently stops writing part of its output is
 * worse than one that owns the file.
 */

import { writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { z } from "zod"

import { ERRORS, type ErrorCode, type ErrorDefinition, errorSlug } from "../src/errors"
import type { RouteDefinition } from "../src/routes"
import { ROUTES } from "../src/routes"
import {
  challengeResponseSchema,
  clientKindSchema,
  createTunnelRequestSchema,
  createTunnelResponseSchema,
  deleteTunnelRequestSchema,
  errorResponseSchema,
  heartbeatRequestSchema,
  heartbeatResponseSchema,
  metaResponseSchema,
  tunnelStatusResponseSchema,
} from "../src/schemas"

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, "..", "..", "..")

const BANNER = "@generated by `pnpm codegen` from packages/contract — do not edit"

/**
 * Schemas that get a **name** in `components.schemas` rather than being inlined into an
 * operation.
 *
 * Naming them is what makes the document usable for code generation: `cargo xtask codegen` emits
 * one Rust type per entry here, and an anonymous inline object would have to be given an invented
 * name that then changes whenever the operation moves.
 */
const COMPONENTS: Record<string, z.ZodType> = {
  ChallengeResponse: challengeResponseSchema,
  ClientKind: clientKindSchema,
  CreateTunnelRequest: createTunnelRequestSchema,
  CreateTunnelResponse: createTunnelResponseSchema,
  HeartbeatRequest: heartbeatRequestSchema,
  HeartbeatResponse: heartbeatResponseSchema,
  DeleteTunnelRequest: deleteTunnelRequestSchema,
  TunnelStatusResponse: tunnelStatusResponseSchema,
  MetaResponse: metaResponseSchema,
  Error: errorResponseSchema,
}

/** The component name for a schema, by identity. */
function componentNameOf(schema: z.ZodType): string | undefined {
  return Object.entries(COMPONENTS).find(([, candidate]) => candidate === schema)?.[0]
}

/** A `$ref` to a named component, or the inline schema if it has no name. */
function schemaRef(schema: z.ZodType): Record<string, unknown> {
  const name = componentNameOf(schema)
  return name ? { $ref: `#/components/schemas/${name}` } : jsonSchema(schema)
}

function entries(): Array<[ErrorCode, ErrorDefinition]> {
  return Object.entries(ERRORS) as Array<[ErrorCode, ErrorDefinition]>
}

/** Escapes a cell so a `|` in prose cannot break the table. */
function cell(text: string): string {
  return text.replaceAll("|", "\\|")
}

function detailsCell(definition: ErrorDefinition): string {
  if (!definition.details || definition.details.length === 0) return "—"
  return definition.details.map((key) => `\`${key}\``).join(", ")
}

function errorsMarkdown(): string {
  const server = entries()
    .filter(([, definition]) => definition.origin === "server")
    // Grouped by status so the table reads as a taxonomy rather than an alphabet.
    .sort(([a, x], [b, y]) => (x.status ?? 0) - (y.status ?? 0) || a.localeCompare(b))
  const client = entries()
    .filter(([, definition]) => definition.origin === "client")
    .sort(([a], [b]) => a.localeCompare(b))

  const serverRows = server
    .map(
      ([code, d]) =>
        `| \`${code}\` | ${d.status} | ${d.retryable ? "yes" : "no"} | ${detailsCell(d)} | ${cell(d.cause)} | ${cell(d.action)} |`,
    )
    .join("\n")

  const clientRows = client
    .map(
      ([code, d]) =>
        `| \`${code}\` | ${d.retryable ? "yes" : "no"} | ${detailsCell(d)} | ${cell(d.cause)} | ${cell(d.action)} |`,
    )
    .join("\n")

  return `---
applies_to:
  - packages/contract/src/errors.ts
  - apps/api/src/errors.ts
  - crates/cli/src/i18n/**
---

<!-- ${BANNER} -->

# Error registry

Every error NPort can return or raise, with a stable code. **Generated from \`packages/contract/src/errors.ts\`** — edit that file and run \`pnpm codegen\`; CI fails on drift.

Four consumers reference these codes, which is why they live in one registry rather than inline in \`docs/API.md\`: the Rust CLI (to pick a translated message and a hint), the Hono error handler (to pick a status), the website's \`/errors/[code]\` pages, and the GitHub issue templates.

**Clients match on \`code\`. Messages are free to change and are translated per ADR-0018.**

## Response shape

\`\`\`jsonc
{
  "error": {
    "code": "SUBDOMAIN_IN_USE",
    "message": "…",
    "details": { },
    "requestId": "…",
    "docsUrl": "https://nport.link/errors/subdomain-in-use"
  }
}
\`\`\`

\`docsUrl\` is \`https://nport.link/errors/<code lowercased, underscores → hyphens>\`.

## Server errors

${server.length} codes. These cross the network and carry an HTTP status.

| Code | Status | Retry | \`details\` | Cause | What the user should do |
| --- | --- | --- | --- | --- | --- |
${serverRows}

### Notes

\`DNS_CONFLICT\` is the only code that signals a possible operational problem rather than user error. It fires when a DNS record exists for a name whose lease is free, meaning a previous teardown failed permanently or something outside NPort created the record. **Reconciliation deliberately does not force-delete these** — see invariant 8. Triage is in \`docs/OPERATIONS.md\`.

\`PROVISION_FAILED\` guarantees compensation ran or is queued via the DO alarm. It never means "you may have a half-created tunnel".

\`UPSTREAM_CLOUDFLARE_ERROR\` never carries upstream text. Raw Cloudflare messages go to Workers logs only; v2 echoed them to anonymous callers, leaking account and zone internals.

## Client errors

${client.length} codes. Raised locally by \`crates/cli\` and \`crates/core\`. They never cross the network, but they share the registry so every failure the user can see has a stable code, a translation key, and a docs anchor.

| Code | Retry | \`details\` | Cause | What the user should do |
| --- | --- | --- | --- | --- |
${clientRows}

\`EDGE_PROTOCOL_ERROR\` is the one to watch. It is the user-visible symptom of the highest-blast-radius failure in the system (\`docs/ARCHITECTURE.md\` §5) and is worded to send people to the issue tracker rather than to their own network configuration.

## Adding an error

1. Add it to \`packages/contract/src/errors.ts\` with its origin, status, retryability, default English message, cause, and action.
2. \`pnpm codegen\` — regenerates this file, \`crates/contract\`, and the website's error pages.
3. Add translations for \`vi\` and \`es\` in \`crates/cli\`.
4. A test asserting the code round-trips already exists and covers the new entry automatically.

Do not add an error whose only difference from an existing one is wording. A code is a contract clients branch on; a message is not.

## Retired v2 error strings

v2 had no codes. For anyone reading old issues or v2 source, the mapping is:

| v2 string the CLI matched | v3 code |
| --- | --- |
| \`SUBDOMAIN_PROTECTED:\` | \`SUBDOMAIN_RESERVED\` |
| \`SUBDOMAIN_IN_USE:\`, \`currently in use\`, \`already exists and is currently active\` | \`SUBDOMAIN_IN_USE\` |
| \`already have a tunnel\`, \`[1013]\` | \`CONCURRENCY_LIMIT\` |
| \`CF API Error: […]\` echoed verbatim | \`UPSTREAM_CLOUDFLARE_ERROR\` |
| a bare \`SyntaxError\` from \`request.json()\` | \`INVALID_REQUEST\` |

Every one of those arrived as **HTTP 500**.
`
}

/** zod → JSON Schema 2020-12, which is what OpenAPI 3.1 speaks natively. */
function jsonSchema(schema: z.ZodType): Record<string, unknown> {
  return z.toJSONSchema(schema, { target: "draft-2020-12", io: "input" }) as Record<string, unknown>
}

function openApiDocument(): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {}

  // Widened from the `as const satisfies` literal union: narrowed, `route.request` does not exist
  // on the members that have no body.
  const routes: readonly RouteDefinition[] = ROUTES

  for (const route of routes) {
    const parameters = route.path.includes("{subdomain}")
      ? [
          {
            name: "subdomain",
            in: "path",
            required: true,
            description: "Normalized server-side before use.",
            schema: { type: "string" },
          },
        ]
      : []

    const responses: Record<string, unknown> = {
      [String(route.successStatus)]: route.response
        ? {
            description: route.summary,
            content: { "application/json": { schema: schemaRef(route.response) } },
          }
        : { description: `${route.summary} No body.` },
    }

    // One response entry per distinct status the route's errors map to, listing which codes can
    // appear. A generated client can then see that a 409 means SUBDOMAIN_IN_USE or DNS_CONFLICT
    // without reading prose.
    const byStatus = new Map<number, ErrorCode[]>()
    for (const code of route.errors) {
      const status = ERRORS[code].status
      if (status === null) continue
      byStatus.set(status, [...(byStatus.get(status) ?? []), code])
    }
    for (const [status, codes] of [...byStatus].sort(([a], [b]) => a - b)) {
      responses[String(status)] = {
        description: codes.map((code) => `\`${code}\``).join(" · "),
        content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
      }
    }

    const operations = paths[route.path] ?? {}
    paths[route.path] = operations
    operations[route.method.toLowerCase()] = {
      summary: route.summary,
      operationId: operationId(route.method, route.path),
      ...(parameters.length > 0 ? { parameters } : {}),
      ...(route.request
        ? {
            requestBody: {
              required: true,
              content: { "application/json": { schema: schemaRef(route.request) } },
            },
          }
        : {}),
      responses,
      // Not part of OpenAPI, but the two facts a client most needs and OpenAPI cannot express.
      "x-idempotent": route.idempotent,
      "x-requires-owner-token": route.requiresOwnerToken,
    }
  }

  return {
    openapi: "3.1.0",
    info: {
      title: "NPort control-plane API",
      version: "1.0.0",
      description:
        "Provisions and reaps tunnels. Not on the tunnel data path. No accounts, no API keys, and no CORS headers — see docs/API.md.",
      license: { name: "MIT", identifier: "MIT" },
    },
    servers: [{ url: "https://api.nport.link", description: "Production" }],
    paths,
    components: {
      schemas: Object.fromEntries(
        Object.entries(COMPONENTS).map(([name, schema]) => [name, jsonSchema(schema)]),
      ),
    },
    "x-generated-by": BANNER,
  }
}

function operationId(method: string, path: string): string {
  const parts = path
    .replace(/^\/v1\//, "")
    .replaceAll("{", "")
    .replaceAll("}", "")
    .split("/")
    .filter(Boolean)
  return (
    method.toLowerCase() +
    parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("")
  )
}

/**
 * The registry as machine-readable data, for `cargo xtask codegen`.
 *
 * Why this exists rather than the Rust side reading the OpenAPI document alone: **an error's HTTP
 * status and retryability are not expressible in JSON Schema.** The document can say the response
 * body has a `code` field with 30 allowed values; it cannot say that `SUBDOMAIN_IN_USE` is a 409
 * and is not worth retrying. Both facts are what the Rust client actually needs, so they travel in
 * their own file rather than being duplicated by hand on the Rust side.
 */
function errorsJson(): Record<string, unknown> {
  return {
    $comment: BANNER,
    errors: Object.fromEntries(
      entries().map(([code, definition]) => [
        code,
        {
          origin: definition.origin,
          status: definition.status,
          retryable: definition.retryable,
          slug: errorSlug(code),
          message: definition.message,
          details: definition.details ?? [],
        },
      ]),
    ),
  }
}

const errorsPath = join(REPO, "docs", "ERRORS.md")
const schemaPath = join(REPO, "schema", "nport-api.openapi.json")
const registryPath = join(REPO, "schema", "errors.json")

await writeFile(errorsPath, errorsMarkdown(), "utf8")
await writeFile(schemaPath, `${JSON.stringify(openApiDocument(), null, 2)}\n`, "utf8")
await writeFile(registryPath, `${JSON.stringify(errorsJson(), null, 2)}\n`, "utf8")

console.log(`wrote ${errorsPath}`)
console.log(`wrote ${schemaPath}`)
console.log(`wrote ${registryPath}`)
console.log(
  `  ${Object.keys(ERRORS).length} error codes, ${ROUTES.length} routes, slugs like ${errorSlug("SUBDOMAIN_IN_USE")}`,
)
