/**
 * Generates everything downstream of the contract.
 *
 * ```
 * pnpm --filter @nport/contract codegen     # or: pnpm codegen, from the root
 * ```
 *
 * Outputs, each with a `@generated` banner and each drift-gated in CI. The list had two of the four
 * for as long as there have been four, which is the stale-list shape `docs/ROADMAP.md` keeps
 * recording — so: **all of them, and what each is for.**
 *
 * - `docs/ERRORS.md`                — the registry as a human-readable table
 * - `schema/nport-api.openapi.json` — the API contract: request and response shapes
 * - `schema/errors.json`            — each code's status and retryability, which JSON Schema cannot say
 * - `schema/subdomain.json`         — the subdomain bounds and reserved lists, for the Rust mirror
 *
 * The last three are read by `cargo xtask codegen`, which emits `crates/contract/src/generated.rs`.
 *
 * Run under `tsx`. Node 22 strips types on its own, but its ESM resolver still requires explicit
 * extensions on relative imports, and `docs/conventions/typescript.md` forbids those — a runner
 * that resolves them is a cheaper fix than extension-annotating every source file to suit a
 * script.
 *
 * **Prose that is not derived from the registry lives in this file**, because these outputs are
 * generated whole rather than having sections spliced into a hand-written file. Splicing needs
 * markers, markers get moved, and a generator that silently stops writing part of its output is
 * worse than one that owns the file.
 */

import { writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { z } from "zod"

import { ERRORS, type ErrorCode, type ErrorDefinition, errorSlug } from "../src/errors"
import type { RouteDefinition } from "../src/routes"
import { REGISTRY_ROUTES, ROUTES } from "../src/routes"
import {
  challengeResponseSchema,
  clientKindSchema,
  createTunnelRequestSchema,
  createTunnelResponseSchema,
  deleteTunnelRequestSchema,
  errorResponseSchema,
  heartbeatRequestSchema,
  heartbeatResponseSchema,
  metaResponseSchema,
  nodeListResponseSchema,
  nodeSchema,
  nodeStatusSchema,
  registerNodeRequestSchema,
  registerNodeResponseSchema,
  tunnelStatusResponseSchema,
} from "../src/schemas"
import {
  MAX_INPUT_LENGTH,
  MAX_LENGTH,
  MIN_LENGTH,
  NPORT_OWNED_PREFIXES,
  REJECTION_REASONS,
  RESERVED_PREFIXES,
  RESERVED_SUBDOMAINS,
  ZONE_SUFFIX,
} from "../src/subdomain"

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, "..", "..", "..")

const BANNER = "@generated by `pnpm codegen` from packages/contract — do not edit"

/**
 * Schemas that get a **name** in `components.schemas` rather than being inlined into an
 * operation.
 *
 * Naming them is what makes the document usable for code generation: `cargo xtask codegen` emits
 * one Rust type per entry here, and an anonymous inline object would have to be given an invented
 * name that then changes whenever the operation moves.
 */
const COMPONENTS: Record<string, z.ZodType> = {
  ChallengeResponse: challengeResponseSchema,
  ClientKind: clientKindSchema,
  CreateTunnelRequest: createTunnelRequestSchema,
  CreateTunnelResponse: createTunnelResponseSchema,
  HeartbeatRequest: heartbeatRequestSchema,
  HeartbeatResponse: heartbeatResponseSchema,
  DeleteTunnelRequest: deleteTunnelRequestSchema,
  TunnelStatusResponse: tunnelStatusResponseSchema,
  MetaResponse: metaResponseSchema,
  Node: nodeSchema,
  NodeStatus: nodeStatusSchema,
  NodeListResponse: nodeListResponseSchema,
  RegisterNodeRequest: registerNodeRequestSchema,
  RegisterNodeResponse: registerNodeResponseSchema,
  Error: errorResponseSchema,
}

/**
 * Every component converted at once, through a zod **registry**, so that a component referencing
 * another emits a `$ref` instead of a copy.
 *
 * Converting one schema at a time inlines everything nested, which was invisible while no component
 * held another: `NodeListResponse.nodes` would have carried an anonymous copy of the node object, and
 * `cargo xtask codegen` would have had to invent a Rust type name for it — or, worse, silently emit
 * something structural. A `$ref` is what makes "naming a component" mean anything.
 *
 * Two consequences worth knowing. Each component gains an `$id`, which is how the refs resolve and is
 * otherwise inert. And `ClientKind` is now referenced rather than inlined at its use site, which
 * removed the need for the Rust emitter's enum-by-value-set lookup — the trick that existed purely
 * because zod used to inline a reused enum with no hint that a named type existed.
 */
const CONVERTED: Record<string, Record<string, unknown>> = (() => {
  const registry = z.registry<{ id: string }>()
  for (const [name, schema] of Object.entries(COMPONENTS)) {
    registry.add(schema, { id: name })
  }
  const { schemas } = z.toJSONSchema(registry, {
    target: "draft-2020-12",
    io: "input",
    uri: (id) => `#/components/schemas/${id}`,
  })
  return schemas as Record<string, Record<string, unknown>>
})()

/** The component name for a schema, by identity. */
function componentNameOf(schema: z.ZodType): string | undefined {
  return Object.entries(COMPONENTS).find(([, candidate]) => candidate === schema)?.[0]
}

/** A `$ref` to a named component, or the inline schema if it has no name. */
function schemaRef(schema: z.ZodType): Record<string, unknown> {
  const name = componentNameOf(schema)
  return name ? { $ref: `#/components/schemas/${name}` } : jsonSchema(schema)
}

/** The components a document actually reaches, so neither document carries the other's types. */
function componentsFor(routes: readonly RouteDefinition[]): Record<string, unknown> {
  const wanted = new Set<string>(["Error"])
  const queue: string[] = []

  for (const route of routes) {
    for (const schema of [route.request, route.response]) {
      const name = schema && componentNameOf(schema)
      if (name) queue.push(name)
    }
  }

  // Transitive, because a reachable component's own `$ref`s are reachable too — `NodeListResponse`
  // pulls `Node`, which pulls `NodeStatus`. Walking rather than listing, so adding a nested schema
  // does not mean remembering to add it here as well.
  while (queue.length > 0) {
    const name = queue.pop()
    if (!name || wanted.has(name)) continue
    wanted.add(name)
    for (const ref of refsWithin(CONVERTED[name])) {
      queue.push(ref)
    }
  }

  return Object.fromEntries(
    Object.entries(CONVERTED)
      .filter(([name]) => wanted.has(name))
      // Sorted, so the output does not reorder when `COMPONENTS` is reordered. A generator whose
      // output moves between runs makes the drift gate useless.
      .sort(([a], [b]) => a.localeCompare(b)),
  )
}

/** Component names referenced anywhere inside one converted schema, at any depth. */
function refsWithin(schema: unknown): string[] {
  if (Array.isArray(schema)) return schema.flatMap(refsWithin)
  if (schema === null || typeof schema !== "object") return []

  const out: string[] = []
  for (const [key, value] of Object.entries(schema)) {
    if (key === "$ref" && typeof value === "string") {
      const name = value.split("/").pop()
      if (name) out.push(name)
    } else {
      out.push(...refsWithin(value))
    }
  }
  return out
}

function entries(): Array<[ErrorCode, ErrorDefinition]> {
  return Object.entries(ERRORS) as Array<[ErrorCode, ErrorDefinition]>
}

/** Escapes a cell so a `|` in prose cannot break the table. */
function cell(text: string): string {
  return text.replaceAll("|", "\\|")
}

function detailsCell(definition: ErrorDefinition): string {
  if (!definition.details || definition.details.length === 0) return "—"
  return definition.details.map((key) => `\`${key}\``).join(", ")
}

function errorsMarkdown(): string {
  const server = entries()
    .filter(([, definition]) => definition.origin === "server")
    // Grouped by status so the table reads as a taxonomy rather than an alphabet.
    .sort(([a, x], [b, y]) => (x.status ?? 0) - (y.status ?? 0) || a.localeCompare(b))
  const client = entries()
    .filter(([, definition]) => definition.origin === "client")
    .sort(([a], [b]) => a.localeCompare(b))

  const serverRows = server
    .map(
      ([code, d]) =>
        `| \`${code}\` | ${d.status} | ${d.retryable ? "yes" : "no"} | ${detailsCell(d)} | ${cell(d.cause)} | ${cell(d.action)} |`,
    )
    .join("\n")

  const clientRows = client
    .map(
      ([code, d]) =>
        `| \`${code}\` | ${d.retryable ? "yes" : "no"} | ${detailsCell(d)} | ${cell(d.cause)} | ${cell(d.action)} |`,
    )
    .join("\n")

  return `---
applies_to:
  - packages/contract/src/errors.ts
  - apps/api/src/errors.ts
  - crates/cli/src/i18n/**
---

<!-- ${BANNER} -->

# Error registry

Every error NPort can return or raise, with a stable code. **Generated from \`packages/contract/src/errors.ts\`** — edit that file and run \`pnpm codegen\`; CI fails on drift.

Four consumers reference these codes, which is why they live in one registry rather than inline in \`docs/API.md\`: the Rust CLI (to pick a translated message and a hint), the Hono error handler (to pick a status), the website's \`/errors/[code]\` pages, and the GitHub issue templates.

**Clients match on \`code\`. Messages are free to change and are translated per ADR-0018.**

## Response shape

\`\`\`jsonc
{
  "error": {
    "code": "SUBDOMAIN_IN_USE",
    "message": "…",
    "details": { },
    "requestId": "…",
    "docsUrl": "https://nport.link/errors/subdomain-in-use"
  }
}
\`\`\`

\`docsUrl\` is \`https://nport.link/errors/<code lowercased, underscores → hyphens>\`.

## Server errors

${server.length} codes. These cross the network and carry an HTTP status.

| Code | Status | Retry | \`details\` | Cause | What the user should do |
| --- | --- | --- | --- | --- | --- |
${serverRows}

### Notes

\`DNS_CONFLICT\` is the only code that signals a possible operational problem rather than user error. It fires when a DNS record exists for a name whose lease is free, meaning a previous teardown failed permanently or something outside NPort created the record. **Reconciliation deliberately does not force-delete these** — see invariant 8. Triage is in \`docs/OPERATIONS.md\`.

\`PROVISION_FAILED\` guarantees compensation ran or is queued via the DO alarm. It never means "you may have a half-created tunnel".

\`UPSTREAM_CLOUDFLARE_ERROR\` never carries upstream text. Raw Cloudflare messages go to Workers logs only; v2 echoed them to anonymous callers, leaking account and zone internals.

## Client errors

${client.length} codes. Raised locally by \`crates/cli\` and \`crates/core\`. They never cross the network, but they share the registry so every failure the user can see has a stable code, a translation key, and a docs anchor.

| Code | Retry | \`details\` | Cause | What the user should do |
| --- | --- | --- | --- | --- |
${clientRows}

\`EDGE_PROTOCOL_ERROR\` is the one to watch. It is the user-visible symptom of the highest-blast-radius failure in the system (\`docs/ARCHITECTURE.md\` §5) and is worded to send people to the issue tracker rather than to their own network configuration.

## Adding an error

1. Add it to \`packages/contract/src/errors.ts\` with its origin, status, retryability, default English message, cause, and action.
2. \`pnpm codegen\` — regenerates this file, \`crates/contract\`, and the website's error pages.
3. Add translations for \`vi\` and \`es\` in \`crates/cli\`.
4. A test asserting the code round-trips already exists and covers the new entry automatically.

Do not add an error whose only difference from an existing one is wording. A code is a contract clients branch on; a message is not.

## Retired v2 error strings

v2 had no codes. For anyone reading old issues or v2 source, the mapping is:

| v2 string the CLI matched | v3 code |
| --- | --- |
| \`SUBDOMAIN_PROTECTED:\` | \`SUBDOMAIN_RESERVED\` |
| \`SUBDOMAIN_IN_USE:\`, \`currently in use\`, \`already exists and is currently active\` | \`SUBDOMAIN_IN_USE\` |
| \`already have a tunnel\`, \`[1013]\` | \`CONCURRENCY_LIMIT\` |
| \`CF API Error: […]\` echoed verbatim | \`UPSTREAM_CLOUDFLARE_ERROR\` |
| a bare \`SyntaxError\` from \`request.json()\` | \`INVALID_REQUEST\` |

Every one of those arrived as **HTTP 500**.
`
}

/** zod → JSON Schema 2020-12, which is what OpenAPI 3.1 speaks natively. */
function jsonSchema(schema: z.ZodType): Record<string, unknown> {
  return z.toJSONSchema(schema, { target: "draft-2020-12", io: "input" }) as Record<string, unknown>
}

/** What distinguishes the two documents: everything except the routes themselves. */
interface ServiceDocument {
  readonly title: string
  readonly description: string
  readonly server: { readonly url: string; readonly description: string }
  readonly routes: readonly RouteDefinition[]
}

function openApiDocument(service: ServiceDocument): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {}

  // Widened from the `as const satisfies` literal union: narrowed, `route.request` does not exist
  // on the members that have no body.
  const routes: readonly RouteDefinition[] = service.routes

  for (const route of routes) {
    const parameters = route.path.includes("{subdomain}")
      ? [
          {
            name: "subdomain",
            in: "path",
            required: true,
            description: "Normalized server-side before use.",
            schema: { type: "string" },
          },
        ]
      : []

    const responses: Record<string, unknown> = {
      [String(route.successStatus)]: route.response
        ? {
            description: route.summary,
            content: { "application/json": { schema: schemaRef(route.response) } },
          }
        : { description: `${route.summary} No body.` },
    }

    // One response entry per distinct status the route's errors map to, listing which codes can
    // appear. A generated client can then see that a 409 means SUBDOMAIN_IN_USE or DNS_CONFLICT
    // without reading prose.
    const byStatus = new Map<number, ErrorCode[]>()
    for (const code of route.errors) {
      const status = ERRORS[code].status
      if (status === null) continue
      byStatus.set(status, [...(byStatus.get(status) ?? []), code])
    }
    for (const [status, codes] of [...byStatus].sort(([a], [b]) => a - b)) {
      responses[String(status)] = {
        description: codes.map((code) => `\`${code}\``).join(" · "),
        content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
      }
    }

    const operations = paths[route.path] ?? {}
    paths[route.path] = operations
    operations[route.method.toLowerCase()] = {
      summary: route.summary,
      operationId: operationId(route.method, route.path),
      ...(parameters.length > 0 ? { parameters } : {}),
      ...(route.request
        ? {
            requestBody: {
              required: true,
              content: { "application/json": { schema: schemaRef(route.request) } },
            },
          }
        : {}),
      responses,
      // Not part of OpenAPI, but the two facts a client most needs and OpenAPI cannot express.
      "x-idempotent": route.idempotent,
      "x-requires-owner-token": route.requiresOwnerToken,
    }
  }

  return {
    openapi: "3.1.0",
    info: {
      title: service.title,
      version: "1.0.0",
      description: service.description,
      license: { name: "MIT", identifier: "MIT" },
    },
    servers: [service.server],
    paths,
    components: { schemas: componentsFor(routes) },
    "x-generated-by": BANNER,
  }
}

function operationId(method: string, path: string): string {
  const parts = path
    .replace(/^\/v1\//, "")
    .replaceAll("{", "")
    .replaceAll("}", "")
    .split("/")
    .filter(Boolean)
  return (
    method.toLowerCase() +
    parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("")
  )
}

/**
 * The registry as machine-readable data, for `cargo xtask codegen`.
 *
 * Why this exists rather than the Rust side reading the OpenAPI document alone: **an error's HTTP
 * status and retryability are not expressible in JSON Schema.** The document can say the response
 * body has a `code` field with 30 allowed values; it cannot say that `SUBDOMAIN_IN_USE` is a 409
 * and is not worth retrying. Both facts are what the Rust client actually needs, so they travel in
 * their own file rather than being duplicated by hand on the Rust side.
 */
function errorsJson(): Record<string, unknown> {
  return {
    $comment: BANNER,
    errors: Object.fromEntries(
      entries().map(([code, definition]) => [
        code,
        {
          origin: definition.origin,
          status: definition.status,
          retryable: definition.retryable,
          slug: errorSlug(code),
          message: definition.message,
          details: definition.details ?? [],
        },
      ]),
    ),
  }
}

/**
 * The subdomain rules as data, for the Rust mirror in `crates/contract/src/subdomain.rs`.
 *
 * **Only the constants, never the logic.** The rules themselves — NFKC, the suffix strip, the
 * hyphen placement — are reimplemented in Rust and pinned by `fixtures/subdomains.json`, because
 * emitting an imperative function into another language is a code generator nobody should write.
 * What is emitted is everything a reader would otherwise retype: the bounds, the zone suffix, and
 * the three lists.
 *
 * The lists are why this file exists. `RESERVED_SUBDOMAINS` has 53 entries, and a second hand-kept
 * copy of it in Rust is the failure mode `docs/ROADMAP.md`'s defects 22, 25 and 29 are all about —
 * a list behind a guarantee, as trustworthy as the last person who remembered to add a name. Adding
 * `paypal` here has to be enough; generating is what makes it enough.
 */
function subdomainJson(): Record<string, unknown> {
  return {
    $comment: BANNER,
    minLength: MIN_LENGTH,
    maxLength: MAX_LENGTH,
    maxInputLength: MAX_INPUT_LENGTH,
    zoneSuffix: ZONE_SUFFIX,
    reservedSubdomains: RESERVED_SUBDOMAINS,
    reservedPrefixes: RESERVED_PREFIXES,
    nportOwnedPrefixes: NPORT_OWNED_PREFIXES,
    rejectionReasons: REJECTION_REASONS,
  }
}

const API_SERVICE: ServiceDocument = {
  title: "NPort control-plane API",
  description:
    "Provisions and reaps tunnels. Not on the tunnel data path. No accounts, no API keys, and no CORS headers — see docs/API.md.",
  server: { url: "https://api.nport.link", description: "Production" },
  routes: ROUTES,
}

const REGISTRY_SERVICE: ServiceDocument = {
  title: "NPort registry API",
  description:
    "The node directory. Lists nodes, accepts anonymous registrations behind proof of work and a DNS TXT domain proof, and probes what it lists. Holds no Cloudflare credentials and provisions nothing — see ADR-0031. Advisory: clients cache the list, so a registry that is down does not stop a tunnel.",
  server: { url: "https://registry.nport.link", description: "Production" },
  routes: REGISTRY_ROUTES,
}

const errorsPath = join(REPO, "docs", "ERRORS.md")
const schemaPath = join(REPO, "schema", "nport-api.openapi.json")
const registrySchemaPath = join(REPO, "schema", "nport-registry.openapi.json")
const registryPath = join(REPO, "schema", "errors.json")
const subdomainPath = join(REPO, "schema", "subdomain.json")

await writeFile(errorsPath, errorsMarkdown(), "utf8")
await writeFile(schemaPath, `${JSON.stringify(openApiDocument(API_SERVICE), null, 2)}\n`, "utf8")
await writeFile(
  registrySchemaPath,
  `${JSON.stringify(openApiDocument(REGISTRY_SERVICE), null, 2)}\n`,
  "utf8",
)
await writeFile(registryPath, `${JSON.stringify(errorsJson(), null, 2)}\n`, "utf8")
await writeFile(subdomainPath, `${JSON.stringify(subdomainJson(), null, 2)}\n`, "utf8")

console.log(`wrote ${errorsPath}`)
console.log(`wrote ${schemaPath}`)
console.log(`wrote ${registrySchemaPath}`)
console.log(`wrote ${registryPath}`)
console.log(`wrote ${subdomainPath}`)
console.log(
  `  ${Object.keys(ERRORS).length} error codes, ${ROUTES.length} routes, slugs like ${errorSlug("SUBDOMAIN_IN_USE")}`,
)
