/**
 * Bindings and per-request context.
 *
 * `Env` mirrors `wrangler.jsonc`. It is hand-written rather than generated by `wrangler types`
 * because the generated file would be a second `@generated` artifact to drift-gate for six values,
 * and a mismatch surfaces immediately as a typecheck failure against the config in review.
 */

/** Secrets. Set with `wrangler secret put`; never in `wrangler.jsonc`, never through CI. */
interface Secrets {
  /** Signs proof-of-work challenges. */
  POW_SECRET: string
  /** Scoped to `Cloudflare Tunnel Write` and `DNS Write`, and nothing else (`docs/OPERATIONS.md`). */
  CF_API_TOKEN: string
  CF_ACCOUNT_ID: string
  CF_ZONE_ID: string
  /**
   * The zone tunnels live under, e.g. `nport.link`.
   *
   * Not a secret, but it travels with the other four so a self-hoster configures one group rather
   * than remembering that one of the five belongs somewhere else (`docs/SELF_HOSTING.md`).
   */
  CF_DOMAIN: string
}

/**
 * Set only by `apps/node/.dev.vars`, which `wrangler dev` reads and `wrangler deploy` does not.
 *
 * Optional and outside `Secrets` on purpose: `missingBindings` must not require it, because a
 * deployment that had it would be the bug. See `src/cloudflare/dev-fake.ts` for the second guard.
 */
interface DevOnly {
  /** `"1"` routes every Cloudflare call to the in-memory fake, so `pnpm dev` provisions offline. */
  FAKE_CLOUDFLARE?: string
}

/**
 * Node identity, for federation (ADR-0031).
 *
 * **All three are optional, and that is the private-deployment case, not an oversight.** A node with
 * no `REGISTRY_URL` never registers and is never listed — which is exactly the self-hosted deployment
 * `docs/SELF_HOSTING.md` already describes, reached by setting nothing rather than by opting out.
 * `missingBindings` therefore does not require them; `src/register.ts` checks the group together and
 * declines as a whole, because a `NODE_ID` with no `PUBLIC_URL` is a half-configured node rather than
 * a private one.
 */
interface NodeIdentity {
  /** This node's id in the directory. Stable across deploys; `[a-z0-9-]`, 3–32 characters. */
  NODE_ID?: string
  /** Where clients reach this node, e.g. `https://api.nport.link`. Must be under `CF_DOMAIN`. */
  PUBLIC_URL?: string
  /** The directory to register with. **Absent means never register.** */
  REGISTRY_URL?: string
  /**
   * What this node reports as its build.
   *
   * Display-only and never verified — the registry stores it and a UI shows it. A stale value costs
   * nothing but a confusing line in a node list, which is why it is a var rather than something
   * derived: nothing here depends on it being right.
   */
  NODE_VERSION?: string
}

/** Plain values from `wrangler.jsonc` § vars. Strings, because Workers vars are strings. */
interface Vars {
  LEASE_TTL_SECONDS: number
  HEARTBEAT_GRACE_SECONDS: number
  MAX_ACTIVE_TUNNELS: number
  MIN_CLIENT_VERSION: string
  /** The floor every caller pays. `SourceQuota` raises it per source from here. */
  POW_DIFFICULTY_BITS: number
  /** The ceiling on automatic escalation. */
  POW_MAX_DIFFICULTY_BITS: number
  MAX_CONCURRENT_PER_SOURCE: number
  MAX_CREATES_PER_HOUR_PER_SOURCE: number
}

export interface Env extends Secrets, Vars, NodeIdentity, DevOnly {
  // Parameterized so the stubs expose their classes' methods. Without the type argument every
  // Durable Object call would be typed `unknown` and a renamed method would fail at runtime rather
  // than at `tsc`. Inline `import(...)` rather than a top-level one because both classes import
  // `Env` from here — a type-only inline import is erased, so the cycle never exists at runtime.
  SUBDOMAIN_LEASE: DurableObjectNamespace<import("./do/subdomain-lease").SubdomainLease>
  REGISTRY: DurableObjectNamespace<import("./do/registry").Registry>
  SOURCE_QUOTA: DurableObjectNamespace<import("./do/source-quota").SourceQuota>
}

export interface Variables {
  /** Echoed in every error envelope so a user can quote one thing in a bug report. */
  requestId: string
  /**
   * `HMAC(ip, secret)` over the address and ASN, computed by **the gateway** and forwarded as
   * `x-nport-source-hash` (ADR-0049). This Worker reads it; it no longer holds the key.
   *
   * Computed once per request and shared, so the limiter and the per-source quota address the same
   * identity. Two independent hashings would be two chances to diverge and give one caller two
   * identities — which is a cap that does not cap.
   */
  sourceHash: string
}
