/**
 * Bindings and per-request context.
 *
 * `Env` mirrors `wrangler.jsonc`. It is hand-written rather than generated by `wrangler types`
 * because the generated file would be a second `@generated` artifact to drift-gate for six values,
 * and a mismatch surfaces immediately as a typecheck failure against the config in review.
 */

/** Secrets. Set with `wrangler secret put`; never in `wrangler.jsonc`, never through CI. */
interface Secrets {
  /** Signs proof-of-work challenges. */
  POW_SECRET: string
  /** Keys the source-identity HMAC. Raw IPs are never stored (rule 11). */
  IP_HASH_SECRET: string
}

/** Plain values from `wrangler.jsonc` § vars. Strings, because Workers vars are strings. */
interface Vars {
  LEASE_TTL_SECONDS: number
  HEARTBEAT_GRACE_SECONDS: number
  MAX_ACTIVE_TUNNELS: number
  MIN_CLIENT_VERSION: string
  POW_DIFFICULTY_BITS: number
}

export interface Env extends Secrets, Vars {
  SUBDOMAIN_LEASE: DurableObjectNamespace
  REGISTRY: DurableObjectNamespace
}

export interface Variables {
  /** Echoed in every error envelope so a user can quote one thing in a bug report. */
  requestId: string
}
