/**
 * Bindings and per-request context.
 *
 * `Env` mirrors `wrangler.jsonc`. It is hand-written rather than generated by `wrangler types`
 * because the generated file would be a second `@generated` artifact to drift-gate for six values,
 * and a mismatch surfaces immediately as a typecheck failure against the config in review.
 */

/** Secrets. Set with `wrangler secret put`; never in `wrangler.jsonc`, never through CI. */
interface Secrets {
  /** Signs proof-of-work challenges. */
  POW_SECRET: string
  /** Keys the source-identity HMAC. Raw IPs are never stored (rule 11). */
  IP_HASH_SECRET: string
  /** Scoped to Account → Cloudflare Tunnel → Edit and Zone → DNS → Edit (`docs/OPERATIONS.md`). */
  CF_API_TOKEN: string
  CF_ACCOUNT_ID: string
  CF_ZONE_ID: string
  /**
   * The zone tunnels live under, e.g. `nport.link`.
   *
   * Not a secret, but it travels with the other four so a self-hoster configures one group rather
   * than remembering that one of the five belongs somewhere else (`docs/SELF_HOSTING.md`).
   */
  CF_DOMAIN: string
}

/** Plain values from `wrangler.jsonc` § vars. Strings, because Workers vars are strings. */
interface Vars {
  LEASE_TTL_SECONDS: number
  HEARTBEAT_GRACE_SECONDS: number
  MAX_ACTIVE_TUNNELS: number
  MIN_CLIENT_VERSION: string
  /** The floor every caller pays. `SourceQuota` raises it per source from here. */
  POW_DIFFICULTY_BITS: number
  /** The ceiling on automatic escalation. */
  POW_MAX_DIFFICULTY_BITS: number
  MAX_CONCURRENT_PER_SOURCE: number
  MAX_CREATES_PER_HOUR_PER_SOURCE: number
}

export interface Env extends Secrets, Vars {
  // Parameterized so the stubs expose their classes' methods. Without the type argument every
  // Durable Object call would be typed `unknown` and a renamed method would fail at runtime rather
  // than at `tsc`. Inline `import(...)` rather than a top-level one because both classes import
  // `Env` from here — a type-only inline import is erased, so the cycle never exists at runtime.
  SUBDOMAIN_LEASE: DurableObjectNamespace<import("./do/subdomain-lease").SubdomainLease>
  REGISTRY: DurableObjectNamespace<import("./do/registry").Registry>
  SOURCE_QUOTA: DurableObjectNamespace<import("./do/source-quota").SourceQuota>
  /**
   * Cloudflare's per-key request-rate limiter, declared in `wrangler.jsonc` § ratelimits.
   *
   * Hand-typed for the same reason `Env` is: `wrangler types` would be a second generated artifact to
   * drift-gate, and this is the whole surface.
   */
  RATE_LIMITER: { limit(options: { key: string }): Promise<{ success: boolean }> }
}

export interface Variables {
  /** Echoed in every error envelope so a user can quote one thing in a bug report. */
  requestId: string
  /**
   * `HMAC(ip, IP_HASH_SECRET)` over the address and ASN, set by the rate-limit middleware.
   *
   * Computed once per request and shared, so the limiter and the per-source quota address the same
   * identity. Two independent hashings would be two chances to diverge and give one caller two
   * identities — which is a cap that does not cap.
   */
  sourceHash: string
}
