/**
 * Renders deploy-time wrangler configs for a **forked node**, from the committed ones.
 *
 *   node scripts/node-config.mjs --domain tunnels.example.com --out /tmp/nport-node
 *
 * ## Why this exists
 *
 * A node operator forks this repository, sets a few secrets, and runs a workflow — no clone, no local
 * wrangler, no Terraform (`docs/ADDING_A_NODE.md`). Two things in the committed configuration cannot
 * survive that unchanged, and neither can be fixed with a command-line flag:
 *
 * 1. **The gateway's `REGISTRY` service binding.** A node deployment has no registry, and Cloudflare
 *    rejects a deploy whose binding names a script that does not exist. It has to be *removed*, not
 *    left pointing at nothing — which is also what makes `/v1/nodes` unrouted there rather than a 404
 *    from an absent service (ADR-0049).
 * 2. **The route.** A custom domain lives in `routes` with `custom_domain: true`, and `wrangler deploy`
 *    has no flag for it. The forker's domain is theirs and cannot be committed here.
 *
 * Everything else — the limits, the Durable Object bindings, the migrations, the rate limiter — is
 * copied through untouched, because it is the same product. This file only removes what a node must not
 * have and fills in what only the operator knows.
 *
 * **Rendered, never committed.** The output goes to a temporary directory and `wrangler deploy --config`
 * reads it there. Writing it back into the tree would put one operator's domain in everybody's fork.
 */

import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"

import { loadWranglerConfig } from "./lib/wrangler-config.mjs"

function argOf(name) {
  const index = process.argv.indexOf(`--${name}`)
  return index === -1 ? undefined : process.argv[index + 1]
}

const domain = argOf("domain")
const out = argOf("out")
const apiSubdomain = argOf("api-subdomain") ?? "api"

if (domain === undefined || out === undefined) {
  console.error("usage: node-config.mjs --domain <apex> --out <dir> [--api-subdomain api]")
  process.exit(2)
}

// Same shape check Terraform's `zone_name` variable applies, so a typo fails here rather than after
// three Workers have deployed.
if (!/^[a-z0-9-]+\.[a-z.]+$/.test(domain)) {
  console.error(`--domain "${domain}" is not a bare apex domain, e.g. tunnels.example.com`)
  process.exit(1)
}

const hostname = `${apiSubdomain}.${domain}`

/**
 * The node: the committed config with its environments dropped.
 *
 * `env` blocks are ours — `staging` names our zone and our node id — and a fork deploying "the staging
 * environment" of somebody else's repository is a confusing thing to offer. A node deployment is the
 * top level, with identity supplied at deploy time as `--var`.
 */
const node = loadWranglerConfig("apps/node/wrangler.jsonc")
delete node.env
// Belt and braces. It is already absent and must stay so: this Worker trusts `x-nport-source-hash`
// because nothing can reach it except the gateway's binding (ADR-0049).
delete node.routes
node.workers_dev = false

/**
 * The gateway: the committed config, minus the registry, plus the operator's hostname.
 */
const gateway = loadWranglerConfig("apps/gateway/wrangler.jsonc")
delete gateway.env
gateway.workers_dev = false
gateway.routes = [{ pattern: hostname, custom_domain: true }]
gateway.services = (gateway.services ?? []).filter((binding) => binding.binding !== "REGISTRY")

if (!gateway.services.some((binding) => binding.binding === "NODE")) {
  console.error(
    "apps/gateway/wrangler.jsonc has no NODE binding — a gateway with no node is useless",
  )
  process.exit(1)
}

mkdirSync(out, { recursive: true })
const banner = `// @generated by scripts/node-config.mjs for ${hostname} — do not commit\n`
writeFileSync(join(out, "node.jsonc"), `${banner}${JSON.stringify(node, null, 2)}\n`, "utf8")
writeFileSync(join(out, "gateway.jsonc"), `${banner}${JSON.stringify(gateway, null, 2)}\n`, "utf8")

console.log(`hostname: ${hostname}`)
console.log(`node:     ${join(out, "node.jsonc")}  (no routes, workers_dev off)`)
console.log(
  `gateway:  ${join(out, "gateway.jsonc")}  (route ${hostname}, ` +
    `${gateway.services.length} binding(s): ${gateway.services.map((b) => b.binding).join(", ")})`,
)

// The one line the operator most needs to see, because it is the difference between a node deployment
// and a master one and it is otherwise invisible until a request 404s.
console.log("\n/v1/nodes will not exist on this deployment — it has no registry, by design.")
