//! @generated by `cargo xtask codegen` — do not edit
//!
//! Source: the two service documents in `schema/`, plus `schema/errors.json` and
//! `schema/subdomain.json` — themselves generated from `packages/contract`. Edit there
//! and run `pnpm codegen && cargo xtask codegen`; CI fails on drift.

use serde::{Deserialize, Serialize};

/// Every error the control plane can return, or the client can raise.
///
/// **Match on this, never on a message.** Messages are translated and free to change;
/// codes are the contract (ADR-0018). `serde` uses the wire spelling.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ErrorCode {
    /// NPort is at capacity. Please try again shortly.
    #[serde(rename = "CAPACITY_EXHAUSTED")]
    CapacityExhausted,
    /// The proof-of-work challenge has expired.
    #[serde(rename = "CHALLENGE_EXPIRED")]
    ChallengeExpired,
    /// This version of NPort is no longer supported.
    #[serde(rename = "CLIENT_TOO_OLD")]
    ClientTooOld,
    /// You already have the maximum number of open tunnels.
    #[serde(rename = "CONCURRENCY_LIMIT")]
    ConcurrencyLimit,
    /// Your configuration file could not be read.
    #[serde(rename = "CONFIG_UNREADABLE")]
    ConfigUnreadable,
    /// Your configuration file could not be written.
    #[serde(rename = "CONFIG_UNWRITABLE")]
    ConfigUnwritable,
    /// You have created too many tunnels this hour.
    #[serde(rename = "CREATE_QUOTA_EXCEEDED")]
    CreateQuotaExceeded,
    /// A conflicting DNS record exists for that subdomain.
    #[serde(rename = "DNS_CONFLICT")]
    DnsConflict,
    /// Could not connect to the Cloudflare edge.
    #[serde(rename = "EDGE_CONNECT_FAILED")]
    EdgeConnectFailed,
    /// Could not find a Cloudflare edge address.
    #[serde(rename = "EDGE_DISCOVERY_FAILED")]
    EdgeDiscoveryFailed,
    /// NPort could not understand the Cloudflare edge's response.
    #[serde(rename = "EDGE_PROTOCOL_ERROR")]
    EdgeProtocolError,
    /// The Cloudflare edge refused this connection.
    #[serde(rename = "EDGE_REGISTRATION_REFUSED")]
    EdgeRegistrationRefused,
    /// Something went wrong on our side.
    #[serde(rename = "INTERNAL")]
    Internal,
    /// That owner token does not match this tunnel.
    #[serde(rename = "INVALID_OWNER_TOKEN")]
    InvalidOwnerToken,
    /// The request body is not valid.
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest,
    /// That subdomain is not allowed.
    #[serde(rename = "INVALID_SUBDOMAIN")]
    InvalidSubdomain,
    /// That tunnel's lease has expired.
    #[serde(rename = "LEASE_EXPIRED")]
    LeaseExpired,
    /// Nothing is listening on that port.
    #[serde(rename = "LOCAL_PORT_CLOSED")]
    LocalPortClosed,
    /// That is not a valid port number.
    #[serde(rename = "LOCAL_PORT_INVALID")]
    LocalPortInvalid,
    /// Your local server refused or reset the request.
    #[serde(rename = "LOCAL_REQUEST_FAILED")]
    LocalRequestFailed,
    /// That NPort node did not answer.
    #[serde(rename = "NODE_UNREACHABLE")]
    NodeUnreachable,
    /// No NPort node is available right now.
    #[serde(rename = "NO_NODE_AVAILABLE")]
    NoNodeAvailable,
    /// The proof-of-work solution is not valid.
    #[serde(rename = "POW_INVALID")]
    PowInvalid,
    /// This request requires a proof-of-work challenge.
    #[serde(rename = "POW_REQUIRED")]
    PowRequired,
    /// The tunnel could not be created. Nothing was left behind.
    #[serde(rename = "PROVISION_FAILED")]
    ProvisionFailed,
    /// Too many requests. Please slow down.
    #[serde(rename = "RATE_LIMITED")]
    RateLimited,
    /// The registry refused this node registration.
    #[serde(rename = "REGISTRATION_REFUSED")]
    RegistrationRefused,
    /// Shutdown took longer than expected.
    #[serde(rename = "SHUTDOWN_TIMEOUT")]
    ShutdownTimeout,
    /// That subdomain is currently in use.
    #[serde(rename = "SUBDOMAIN_IN_USE")]
    SubdomainInUse,
    /// That subdomain is reserved.
    #[serde(rename = "SUBDOMAIN_RESERVED")]
    SubdomainReserved,
    /// The tunnel connection was lost and could not be re-established.
    #[serde(rename = "TUNNEL_LOST")]
    TunnelLost,
    /// No tunnel exists for that subdomain.
    #[serde(rename = "TUNNEL_NOT_FOUND")]
    TunnelNotFound,
    /// An upstream provider request failed.
    #[serde(rename = "UPSTREAM_CLOUDFLARE_ERROR")]
    UpstreamCloudflareError,
}

impl ErrorCode {
    /// Every code, alphabetically.
    pub const ALL: [Self; 33] = [
        Self::CapacityExhausted,
        Self::ChallengeExpired,
        Self::ClientTooOld,
        Self::ConcurrencyLimit,
        Self::ConfigUnreadable,
        Self::ConfigUnwritable,
        Self::CreateQuotaExceeded,
        Self::DnsConflict,
        Self::EdgeConnectFailed,
        Self::EdgeDiscoveryFailed,
        Self::EdgeProtocolError,
        Self::EdgeRegistrationRefused,
        Self::Internal,
        Self::InvalidOwnerToken,
        Self::InvalidRequest,
        Self::InvalidSubdomain,
        Self::LeaseExpired,
        Self::LocalPortClosed,
        Self::LocalPortInvalid,
        Self::LocalRequestFailed,
        Self::NodeUnreachable,
        Self::NoNodeAvailable,
        Self::PowInvalid,
        Self::PowRequired,
        Self::ProvisionFailed,
        Self::RateLimited,
        Self::RegistrationRefused,
        Self::ShutdownTimeout,
        Self::SubdomainInUse,
        Self::SubdomainReserved,
        Self::TunnelLost,
        Self::TunnelNotFound,
        Self::UpstreamCloudflareError,
    ];

    /// The wire spelling, e.g. `SUBDOMAIN_IN_USE`.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::CapacityExhausted => "CAPACITY_EXHAUSTED",
            Self::ChallengeExpired => "CHALLENGE_EXPIRED",
            Self::ClientTooOld => "CLIENT_TOO_OLD",
            Self::ConcurrencyLimit => "CONCURRENCY_LIMIT",
            Self::ConfigUnreadable => "CONFIG_UNREADABLE",
            Self::ConfigUnwritable => "CONFIG_UNWRITABLE",
            Self::CreateQuotaExceeded => "CREATE_QUOTA_EXCEEDED",
            Self::DnsConflict => "DNS_CONFLICT",
            Self::EdgeConnectFailed => "EDGE_CONNECT_FAILED",
            Self::EdgeDiscoveryFailed => "EDGE_DISCOVERY_FAILED",
            Self::EdgeProtocolError => "EDGE_PROTOCOL_ERROR",
            Self::EdgeRegistrationRefused => "EDGE_REGISTRATION_REFUSED",
            Self::Internal => "INTERNAL",
            Self::InvalidOwnerToken => "INVALID_OWNER_TOKEN",
            Self::InvalidRequest => "INVALID_REQUEST",
            Self::InvalidSubdomain => "INVALID_SUBDOMAIN",
            Self::LeaseExpired => "LEASE_EXPIRED",
            Self::LocalPortClosed => "LOCAL_PORT_CLOSED",
            Self::LocalPortInvalid => "LOCAL_PORT_INVALID",
            Self::LocalRequestFailed => "LOCAL_REQUEST_FAILED",
            Self::NodeUnreachable => "NODE_UNREACHABLE",
            Self::NoNodeAvailable => "NO_NODE_AVAILABLE",
            Self::PowInvalid => "POW_INVALID",
            Self::PowRequired => "POW_REQUIRED",
            Self::ProvisionFailed => "PROVISION_FAILED",
            Self::RateLimited => "RATE_LIMITED",
            Self::RegistrationRefused => "REGISTRATION_REFUSED",
            Self::ShutdownTimeout => "SHUTDOWN_TIMEOUT",
            Self::SubdomainInUse => "SUBDOMAIN_IN_USE",
            Self::SubdomainReserved => "SUBDOMAIN_RESERVED",
            Self::TunnelLost => "TUNNEL_LOST",
            Self::TunnelNotFound => "TUNNEL_NOT_FOUND",
            Self::UpstreamCloudflareError => "UPSTREAM_CLOUDFLARE_ERROR",
        }
    }

    /// The docs slug, e.g. `subdomain-in-use`.
    #[must_use]
    pub const fn slug(self) -> &'static str {
        match self {
            Self::CapacityExhausted => "capacity-exhausted",
            Self::ChallengeExpired => "challenge-expired",
            Self::ClientTooOld => "client-too-old",
            Self::ConcurrencyLimit => "concurrency-limit",
            Self::ConfigUnreadable => "config-unreadable",
            Self::ConfigUnwritable => "config-unwritable",
            Self::CreateQuotaExceeded => "create-quota-exceeded",
            Self::DnsConflict => "dns-conflict",
            Self::EdgeConnectFailed => "edge-connect-failed",
            Self::EdgeDiscoveryFailed => "edge-discovery-failed",
            Self::EdgeProtocolError => "edge-protocol-error",
            Self::EdgeRegistrationRefused => "edge-registration-refused",
            Self::Internal => "internal",
            Self::InvalidOwnerToken => "invalid-owner-token",
            Self::InvalidRequest => "invalid-request",
            Self::InvalidSubdomain => "invalid-subdomain",
            Self::LeaseExpired => "lease-expired",
            Self::LocalPortClosed => "local-port-closed",
            Self::LocalPortInvalid => "local-port-invalid",
            Self::LocalRequestFailed => "local-request-failed",
            Self::NodeUnreachable => "node-unreachable",
            Self::NoNodeAvailable => "no-node-available",
            Self::PowInvalid => "pow-invalid",
            Self::PowRequired => "pow-required",
            Self::ProvisionFailed => "provision-failed",
            Self::RateLimited => "rate-limited",
            Self::RegistrationRefused => "registration-refused",
            Self::ShutdownTimeout => "shutdown-timeout",
            Self::SubdomainInUse => "subdomain-in-use",
            Self::SubdomainReserved => "subdomain-reserved",
            Self::TunnelLost => "tunnel-lost",
            Self::TunnelNotFound => "tunnel-not-found",
            Self::UpstreamCloudflareError => "upstream-cloudflare-error",
        }
    }

    /// HTTP status, or `None` for a client-side code that never crosses the network.
    #[must_use]
    pub const fn http_status(self) -> Option<u16> {
        match self {
            Self::CapacityExhausted => Some(503),
            Self::ChallengeExpired => Some(400),
            Self::ClientTooOld => Some(426),
            Self::ConcurrencyLimit => Some(429),
            Self::ConfigUnreadable => None,
            Self::ConfigUnwritable => None,
            Self::CreateQuotaExceeded => Some(429),
            Self::DnsConflict => Some(409),
            Self::EdgeConnectFailed => None,
            Self::EdgeDiscoveryFailed => None,
            Self::EdgeProtocolError => None,
            Self::EdgeRegistrationRefused => None,
            Self::Internal => Some(500),
            Self::InvalidOwnerToken => Some(403),
            Self::InvalidRequest => Some(400),
            Self::InvalidSubdomain => Some(400),
            Self::LeaseExpired => Some(410),
            Self::LocalPortClosed => None,
            Self::LocalPortInvalid => None,
            Self::LocalRequestFailed => None,
            Self::NodeUnreachable => None,
            Self::NoNodeAvailable => None,
            Self::PowInvalid => Some(400),
            Self::PowRequired => Some(428),
            Self::ProvisionFailed => Some(500),
            Self::RateLimited => Some(429),
            Self::RegistrationRefused => Some(403),
            Self::ShutdownTimeout => None,
            Self::SubdomainInUse => Some(409),
            Self::SubdomainReserved => Some(403),
            Self::TunnelLost => None,
            Self::TunnelNotFound => Some(404),
            Self::UpstreamCloudflareError => Some(502),
        }
    }

    /// Whether retrying the same request can succeed.
    ///
    /// Not advisory — `crates/cli` branches on it, so a wrong value either hammers a
    /// permanent failure or gives up on a transient one.
    #[must_use]
    pub const fn is_retryable(self) -> bool {
        match self {
            Self::CapacityExhausted => true,
            Self::ChallengeExpired => true,
            Self::ClientTooOld => false,
            Self::ConcurrencyLimit => true,
            Self::ConfigUnreadable => false,
            Self::ConfigUnwritable => false,
            Self::CreateQuotaExceeded => true,
            Self::DnsConflict => false,
            Self::EdgeConnectFailed => true,
            Self::EdgeDiscoveryFailed => true,
            Self::EdgeProtocolError => false,
            Self::EdgeRegistrationRefused => true,
            Self::Internal => true,
            Self::InvalidOwnerToken => false,
            Self::InvalidRequest => false,
            Self::InvalidSubdomain => false,
            Self::LeaseExpired => false,
            Self::LocalPortClosed => false,
            Self::LocalPortInvalid => false,
            Self::LocalRequestFailed => false,
            Self::NodeUnreachable => true,
            Self::NoNodeAvailable => true,
            Self::PowInvalid => false,
            Self::PowRequired => false,
            Self::ProvisionFailed => true,
            Self::RateLimited => true,
            Self::RegistrationRefused => false,
            Self::ShutdownTimeout => false,
            Self::SubdomainInUse => false,
            Self::SubdomainReserved => false,
            Self::TunnelLost => false,
            Self::TunnelNotFound => false,
            Self::UpstreamCloudflareError => true,
        }
    }

    /// Parses a wire code. Unknown codes are `None`, never a guess.
    #[must_use]
    pub fn parse(code: &str) -> Option<Self> {
        match code {
            "CAPACITY_EXHAUSTED" => Some(Self::CapacityExhausted),
            "CHALLENGE_EXPIRED" => Some(Self::ChallengeExpired),
            "CLIENT_TOO_OLD" => Some(Self::ClientTooOld),
            "CONCURRENCY_LIMIT" => Some(Self::ConcurrencyLimit),
            "CONFIG_UNREADABLE" => Some(Self::ConfigUnreadable),
            "CONFIG_UNWRITABLE" => Some(Self::ConfigUnwritable),
            "CREATE_QUOTA_EXCEEDED" => Some(Self::CreateQuotaExceeded),
            "DNS_CONFLICT" => Some(Self::DnsConflict),
            "EDGE_CONNECT_FAILED" => Some(Self::EdgeConnectFailed),
            "EDGE_DISCOVERY_FAILED" => Some(Self::EdgeDiscoveryFailed),
            "EDGE_PROTOCOL_ERROR" => Some(Self::EdgeProtocolError),
            "EDGE_REGISTRATION_REFUSED" => Some(Self::EdgeRegistrationRefused),
            "INTERNAL" => Some(Self::Internal),
            "INVALID_OWNER_TOKEN" => Some(Self::InvalidOwnerToken),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            "INVALID_SUBDOMAIN" => Some(Self::InvalidSubdomain),
            "LEASE_EXPIRED" => Some(Self::LeaseExpired),
            "LOCAL_PORT_CLOSED" => Some(Self::LocalPortClosed),
            "LOCAL_PORT_INVALID" => Some(Self::LocalPortInvalid),
            "LOCAL_REQUEST_FAILED" => Some(Self::LocalRequestFailed),
            "NODE_UNREACHABLE" => Some(Self::NodeUnreachable),
            "NO_NODE_AVAILABLE" => Some(Self::NoNodeAvailable),
            "POW_INVALID" => Some(Self::PowInvalid),
            "POW_REQUIRED" => Some(Self::PowRequired),
            "PROVISION_FAILED" => Some(Self::ProvisionFailed),
            "RATE_LIMITED" => Some(Self::RateLimited),
            "REGISTRATION_REFUSED" => Some(Self::RegistrationRefused),
            "SHUTDOWN_TIMEOUT" => Some(Self::ShutdownTimeout),
            "SUBDOMAIN_IN_USE" => Some(Self::SubdomainInUse),
            "SUBDOMAIN_RESERVED" => Some(Self::SubdomainReserved),
            "TUNNEL_LOST" => Some(Self::TunnelLost),
            "TUNNEL_NOT_FOUND" => Some(Self::TunnelNotFound),
            "UPSTREAM_CLOUDFLARE_ERROR" => Some(Self::UpstreamCloudflareError),
            _ => None,
        }
    }
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A stateless proof-of-work challenge.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChallengeResponse {
    /// Opaque, HMAC-signed, self-validating. Nothing is stored server-side.
    pub challenge: String,
    /// Required leading zero bits. Raised under load.
    pub difficulty: u64,
    /// After this, solving it is pointless.
    #[serde(rename = "expiresAt")]
    pub expires_at: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ClientKind {
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "desktop")]
    Desktop,
}

/// Claim a subdomain and provision a tunnel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTunnelRequest {
    /// The `challenge` value from `GET /v1/challenge`.
    pub challenge: String,
    pub client: ClientKind,
    /// A solution satisfying the challenge's difficulty.
    pub nonce: String,
    /// Desired subdomain. Normalized server-side; omit to have one generated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subdomain: Option<String>,
}

/// A provisioned tunnel. Both tokens are shown exactly once.
#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTunnelResponse {
    /// Server-authoritative. The client only displays it.
    #[serde(rename = "expiresAt")]
    pub expires_at: u64,
    /// 256-bit bearer proof for this lease. Returned ONCE; only its SHA-256 is stored.
    #[serde(rename = "ownerToken")]
    pub owner_token: String,
    /// The normalized subdomain that was claimed.
    pub subdomain: String,
    /// Cloudflare's tunnel UUID.
    #[serde(rename = "tunnelId")]
    pub tunnel_id: String,
    /// Connector credential. Returned ONCE. Never logged, never in argv.
    #[serde(rename = "tunnelToken")]
    pub tunnel_token: String,
    /// The public HTTPS URL. Ready within a few seconds, not instantly.
    pub url: String,
}

impl std::fmt::Debug for CreateTunnelResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CreateTunnelResponse")
            .field("expires_at", &self.expires_at)
            .field("owner_token", &"<redacted>")
            .field("subdomain", &self.subdomain)
            .field("tunnel_id", &self.tunnel_id)
            .field("tunnel_token", &"<redacted>")
            .field("url", &self.url)
            .finish()
    }
}

/// Release a lease and tear the tunnel down. Idempotent.
#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteTunnelRequest {
    /// The `ownerToken` returned when the tunnel was created.
    #[serde(rename = "ownerToken")]
    pub owner_token: String,
}

impl std::fmt::Debug for DeleteTunnelRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DeleteTunnelRequest")
            .field("owner_token", &"<redacted>")
            .finish()
    }
}

/// Renew a lease.
#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HeartbeatRequest {
    /// Proves this caller created the lease.
    #[serde(rename = "ownerToken")]
    pub owner_token: String,
}

impl std::fmt::Debug for HeartbeatRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("HeartbeatRequest")
            .field("owner_token", &"<redacted>")
            .finish()
    }
}

/// The lease's current expiry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HeartbeatResponse {
    /// Authoritative. Clients correct their countdown from this rather than counting locally.
    #[serde(rename = "expiresAt")]
    pub expires_at: u64,
}

/// Limits, discovered rather than hardcoded, so they can be tuned without a client release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetaResponse {
    /// Live tunnels on this node right now.
    #[serde(rename = "activeTunnels")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_tunnels: Option<u64>,
    #[serde(rename = "heartbeatIntervalMs")]
    pub heartbeat_interval_ms: u64,
    /// This node's global cap. With `activeTunnels`, the headroom a client selects on.
    #[serde(rename = "maxActiveTunnels")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_active_tunnels: Option<u64>,
    #[serde(rename = "maxConcurrentPerSource")]
    pub max_concurrent_per_source: u64,
    #[serde(rename = "maxCreatesPerHourPerSource")]
    pub max_creates_per_hour_per_source: u64,
    /// Below this, requests get 426 CLIENT_TOO_OLD.
    #[serde(rename = "minClientVersion")]
    pub min_client_version: String,
    #[serde(rename = "powDifficulty")]
    pub pow_difficulty: u64,
    #[serde(rename = "tunnelDurationMs")]
    pub tunnel_duration_ms: u64,
}

/// A node in the directory, as the registry last observed it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Node {
    /// From this node's `/v1/meta` at the last probe. Absent means unknown, not zero.
    #[serde(rename = "activeTunnels")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_tunnels: Option<u64>,
    /// The domain this node issues tunnels on. One domain per node — a zone cannot span accounts.
    pub domain: String,
    /// Stable, operator-chosen. Appears in `--node` and in `details.nodeId`.
    pub id: String,
    /// When the registry last got an answer out of this node.
    #[serde(rename = "lastProbedAt")]
    pub last_probed_at: u64,
    #[serde(rename = "maxActiveTunnels")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_active_tunnels: Option<u64>,
    /// Advertised hint only, e.g. `apac`. Never verified; never used for selection.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    pub status: NodeStatus,
    /// The node's control-plane base URL, e.g. `https://api.nport.link`.
    pub url: String,
    /// The node's build version, as it declared at registration.
    pub version: String,
}

/// The directory. Includes down and full nodes, so a client can show them as unavailable.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeListResponse {
    pub nodes: Vec<Node>,
    #[serde(rename = "refreshAfterMs")]
    pub refresh_after_ms: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeStatus {
    #[serde(rename = "up")]
    Up,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "down")]
    Down,
}

/// Register or refresh a node. Carries no capacity claim — the registry probes `/v1/meta` for that.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterNodeRequest {
    pub challenge: String,
    pub domain: String,
    pub id: String,
    pub nonce: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    pub url: String,
    pub version: String,
}

/// The entry as stored, including the capacity and status the registry observed rather than what was sent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterNodeResponse {
    pub node: Node,
}

/// Public status. Deliberately carries nothing an attacker could use.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TunnelStatusResponse {
    pub active: bool,
    /// Milliseconds since the Unix epoch, UTC.
    #[serde(rename = "expiresAt")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<u64>,
    /// The normalized subdomain that was claimed.
    pub subdomain: String,
}

// ── Subdomain rules, from `schema/subdomain.json` ─────────────────────────────────

/// The shortest claimable name. Ours, not DNS's — it keeps the namespace sane.
pub const MIN_SUBDOMAIN_LENGTH: usize = 3;
/// The DNS label limit.
pub const MAX_SUBDOMAIN_LENGTH: usize = 63;
/// The longest **raw input** normalization will look at, before the zone suffix is stripped.
pub const MAX_SUBDOMAIN_INPUT_LENGTH: usize = 329;
/// Stripped during normalization, so pasting a whole hostname works.
pub const ZONE_SUFFIX: &str = ".nport.link";

/// Names nobody may claim.
pub const RESERVED_SUBDOMAINS: [&str; 53] = [
    "api",
    "www",
    "mail",
    "smtp",
    "imap",
    "pop",
    "ns",
    "ns1",
    "ns2",
    "mx",
    "_acme-challenge",
    "_dmarc",
    "_domainkey",
    "app",
    "docs",
    "doc",
    "blog",
    "status",
    "cdn",
    "assets",
    "static",
    "admin",
    "dashboard",
    "staging",
    "dev",
    "test",
    "demo",
    "beta",
    "help",
    "support",
    "nport",
    "login",
    "signin",
    "signup",
    "logout",
    "secure",
    "verify",
    "verification",
    "account",
    "accounts",
    "billing",
    "payment",
    "payments",
    "invoice",
    "paypal",
    "stripe",
    "wallet",
    "bank",
    "auth",
    "oauth",
    "sso",
    "password",
    "reset",
];

/// Prefixes nobody may claim.
pub const RESERVED_PREFIXES: [&str; 3] = ["smoke-", "nport-", "_"];

/// The reserved prefixes that are NPort's own, and therefore ours to reap (ADR-0036).
pub const NPORT_OWNED_PREFIXES: [&str; 2] = ["smoke-", "nport-"];

/// Every `details.reason` a refusal can carry, in the contract's own spelling.
pub const REJECTION_REASONS: [&str; 8] = [
    "empty",
    "too-short",
    "too-long",
    "invalid-characters",
    "leading-or-trailing-hyphen",
    "double-hyphen-prefix",
    "reserved",
    "reserved-prefix",
];
